- iXBRLViewerPlugin/viewer/src/js/inspector.js
- iXBRLViewerPlugin/viewer/src/js/viewer.js
Substantially improve search performance by highlighting facts in the iXBRL document in a single pass, rather than individually.  Previously searches with a large number of results on a large document could lead to the UI locking up for a number of seconds.
This also limits the number of results shown to 100, although this could safely be higher with the above fix.
> Improve search performance

- iXBRLViewerPlugin/viewer/src/js/index.js
- iXBRLViewerPlugin/viewer/src/js/inspector.js
- iXBRLViewerPlugin/viewer/src/js/report.js
- iXBRLViewerPlugin/viewer/src/js/report.test.js
- iXBRLViewerPlugin/viewer/src/js/util.js
If the URL to the viewer contains a fragment identifier starting with "#f-" treat the remainder as a fact ID and focus the viewer on that fact when opening the viewer, e.g.:
https://example.com/mydocument-viewer.html#f-fact1
The fragment identifier is updated whenever a fact is selected.
This allows deep linking to facts within a report - potentially useful where the viewer is hosted on a website/intranet and users want to share links to specific facts, or where you are reviewing a 
validation report and want to be able to link to relevant facts in context.
> Fact deep link

- iXBRLViewerPlugin/viewer/src/js/index.js
- iXBRLViewerPlugin/viewer/src/less/core.less
- iXBRLViewerPlugin/viewer/src/less/inspector.less
- iXBRLViewerPlugin/viewer/src/less/text-mixins.less
* Ensure that tables use the correct size font.
* Explicitly delete any style attribute on the body tag once the
contents have been copied into the iframe to avoid any interference with
the viewer.
* Declare font styles on #ixv not body, so that they're correct even
before the iXBRL is reparented and any body@style attribute deleted.
> Font size/style fixes

- iXBRLViewerPlugin/viewer/src/html/inspector.html
- iXBRLViewerPlugin/viewer/src/js/accordian.js
- iXBRLViewerPlugin/viewer/src/js/inspector.js
- iXBRLViewerPlugin/viewer/src/js/viewer.js
- iXBRLViewerPlugin/viewer/src/less/inspector.less
- iXBRLViewerPlugin/viewer/webpack.common.js
Make the viewer work when treated as XHTML.  iXBRL filings are often served with an XHTML extension or content type, which will put the browser into standards compliant rendering mode, and enforce XML validity.  
For most filings the rendering mode makes little or no difference, but for others it can substantially affect the rendering.
This PR makes the viewer itself XHTML valid, which means that it can be served using an XHTML extension/mime-type, with the result that the iXBRL file will also be treated as XHTML.
The SEC serves iXBRL with a .htm extension, so it is treated as HTML, but UK Companies House use .xhtml.
> XHTML support

- Makefile
- README.md
- iXBRLViewerPlugin/viewer/webpack.common.js
- package.json
Resolves the issues reported on issue 12 with the viewer not building on Windows.
Now uses scripts in package.json to perform the build.
Updated build documentation to use "npm run ... " rather than "make ...".
Also added note about not using the release builds of Arelle due to missing library dependency.
> Issue 12 build fixes

- iXBRLViewerPlugin/viewer/src/js/fact.js
- iXBRLViewerPlugin/viewer/src/js/fact.test.js
- iXBRLViewerPlugin/viewer/src/js/report.js
- iXBRLViewerPlugin/viewer/src/js/viewer.js
If a fact appears to contain escaped HTML tags, show just the text content of that HTML, rather than the HTML source.  This fixes XMAS-3842.
A fact is determined to contain HTML if it starts with optional whitespace, followed by "<", QName, then ">", "/>" or space.
Ideally we'd check the fact datatype too, but we don't currently have access to datatype information in the viewer, and the chance (and downside) of a false positive seems minimal.
> XMAS-3842 - Fix for facts with HTML content

- iXBRLViewerPlugin/iXBRLViewer.py
- iXBRLViewerPlugin/viewer/src/js/aspect.js
- iXBRLViewerPlugin/viewer/src/js/fact.js
- iXBRLViewerPlugin/viewer/src/js/fact.test.js
- iXBRLViewerPlugin/viewer/src/js/inspector.js
Allow numeric facts to have a unit of "null" so that we can load draft documents, even though this is technically invalid XBRL.  The presence of the unit aspect is used by the viewer to identify numeric facts, so the plugin now uses a unit of "null" in the JSON for this case.  Fixes XMAS 3575.
> XMAS-3575 - Tolerate missing unit on numeric facts

- Makefile
- iXBRLViewerPlugin/iXBRLViewer.py
- iXBRLViewerPlugin/xhtmlserialize.py
- tests/unit_tests/iXBRLViewerPlugin/mock_arelle.py
- tests/unit_tests/iXBRLViewerPlugin/test_iXBRLViewer.py
- tests/unit_tests/iXBRLViewerPlugin/test_xhtmlserialize.py
Avoid self-closing tags for HTML elements that can have content (e.g. span and div).
Fixes XMAS-3986
> Avoid self closing tags

- iXBRLViewerPlugin/viewer/src/js/viewer.js
Listen to `postMessage()` in order for the ixbrl viewer to be driven by consumers without requiring consumers to have direct access to the javascript source code.
This adds handling for showing a Fact by identifier.
It does this by listening to `window.onMessage`. Integrators can call window `postMessage(msg, origin)`.
The format of this message is JSON. The only handled message introduced in this PR is of the following format:
```
{
"task": "SHOW_FACT",
"factId": "the fact id"
}
```
Invalid JSON message will throw an exception
A JSON message that does not define a 'task' attribute or does not have a task value of "SHOW_FACT" will be ignored.
An invalid factId will be ignored.
This can be tested [by downloading this zip](https://drive.google.com/open?id=1nJrbVuhVI3wfpaYMZJ5OAy4Q14P5vy57), …
> XMAS-4131 Allow postMessage() events to navigate to a Fact by identifier

- iXBRLViewerPlugin/viewer/src/js/fact.test.js
- iXBRLViewerPlugin/viewer/src/js/report.js
Attempting to get a non-existent label was returning "undefined" as a string rather than a value, causing "undefined" to be displayed as the label.
This fixes that, so the documentation label is not shown at all in this case.
On behalf of XII.
> Fix undefined documentation label

- iXBRLViewerPlugin/viewer/src/html/inspector.html
- iXBRLViewerPlugin/viewer/src/js/menu.js
- iXBRLViewerPlugin/viewer/src/less/menu.less
If the report includes a very large number of languages, they may not fit on the page.  This commit adds a scroll bar in this case.
On behalf of XII.
> Add scroll bar to menu if list of options is too long

- iXBRLViewerPlugin/iXBRLViewer.py
- tests/unit_tests/iXBRLViewerPlugin/test_iXBRLViewer.py
This is required for iXBRL/XHTML validity.
> Add type attribute to script tag

- iXBRLViewerPlugin/viewer/src/js/identifiers.js
This is used to provide links to authoritative entity information for known entity schemes.
> Switch to GLEIF v2 API for LEI lookup, add support for UK company numbers

- iXBRLViewerPlugin/viewer/src/html/fact-details.html
- iXBRLViewerPlugin/viewer/src/html/inspector.html
- iXBRLViewerPlugin/viewer/src/js/accordian.js
- iXBRLViewerPlugin/viewer/src/js/aspect.js
- iXBRLViewerPlugin/viewer/src/js/factset.js
- iXBRLViewerPlugin/viewer/src/js/factset.test.js
- iXBRLViewerPlugin/viewer/src/js/inspector.js
- iXBRLViewerPlugin/viewer/src/js/viewer.js
- iXBRLViewerPlugin/viewer/src/less/accordian.less
- iXBRLViewerPlugin/viewer/src/less/inspector.less
If a piece of text has been tagged more than once, clicking on it will now show all facts which it forms a part of in an accordian.
The code will generate a minimally unique label for each fact in the set to use as a title for the accordian.  It runs through each dimension on the facts, and adds the value for that dimension for all facts if there are any differences between the facts.  It does this as many times as necessary to get unique labels for each fact.  The first dimension it tries is "concept", an the second is "period".  This means that for common cases, the facts will be labelled by just concept, or just period.
The use of the accordian here is perhaps a little suspect, as the subsequent sections (references and calculations) are linked to the individual facts, and so will …
> Show all facts when selecting a nested tag

- iXBRLViewerPlugin/viewer/src/js/inspector.js
If you select a text fact with a large amount of text, it should appear truncated in the inspector with an ellipsis button that will show the full text.
The changes for to add support for nested facts stopped the ellipsis from ever being displayed.  This is now fixed.
> Fix UI for truncation of text in the inspector

- iXBRLViewerPlugin/iXBRLViewer.py
- iXBRLViewerPlugin/viewer/src/html/inspector.html
- iXBRLViewerPlugin/viewer/src/js/index.js
- iXBRLViewerPlugin/viewer/src/less/inspector.less
- iXBRLViewerPlugin/viewer/src/less/loader.less
- tests/unit_tests/iXBRLViewerPlugin/test_iXBRLViewer.py
ID attribute on script tag is invalid according to the iXBRL/XHTML schema.  We now locate the taxonomy data by its position in the document, and report an error in the loading mask if the element is not what we expect.
Fixes #30
> Remove ID attribute from JSON data <script> tag

- iXBRLViewerPlugin/iXBRLViewer.py
- tests/unit_tests/iXBRLViewerPlugin/test_iXBRLViewer.py
This removes parent-child relationship information from the taxonomy data included in the viewer files.  This information was not being used by the viewer, and was adding a substantial amount of size to the file, as information (labels, references) about all concepts in the presentation tree is also included.
This is particularly relevant on UK filings which do not use extensions and so include the base taxonomy presentation linkbase which covers all concepts in the taxonomy.
If we re-add this in the future, we should make it more selective (e.g. excluding ELRs which don't have any concepts, and not including labels/references for unused concepts).
> Remove parent-child relationship information

- iXBRLViewerPlugin/viewer/src/less/inspector.less
Add a border to the left hand side of the inspector.  This provides visual separation between the document and the inspector on very short documents, where there is no scroll bar shown, or on platforms with scroll bars that aren't always visible, or don't run the full height of the screen (e.g. firefox on Linux).
On a normal length document on Chrome (on Linux, at least), the new border is pretty much invisible.
> Add border to LHS of inspector

- iXBRLViewerPlugin/viewer/src/js/aspect.js
- iXBRLViewerPlugin/viewer/src/js/aspect.test.js
Where facts are using Euros, display a Euro symbol (€) rather than iso4217:EUR.
> EUR currency symbol support

- iXBRLViewerPlugin/viewer/src/js/fact.js
- iXBRLViewerPlugin/viewer/src/js/fact.test.js
Infinite decimals was incorrectly treated as zero decimals when deciding how many decimal places to display, causing numbers with a decimal part to be truncated (e.g. 0.0125 displayed as "0")
With this fix, the viewer will show whatever digits are present.
> Fix display of decimal numbers with infinite decimals

- iXBRLViewerPlugin/viewer/src/js/viewer.js
Fixes #52 whereby using "highlight all facts" on any document with a continuation element in it will log an error, and no further elements will be highlighted.  This can be seen on the "continuations" sample.
> Fix "highlight all facts" in documents containing continuations

- iXBRLViewerPlugin/viewer/src/js/tableExport.js
This fixes a bug where table export failed due to hidden cells.  These were previously included in the table data, leading to uneven row lengths, which the code did not cope with gracefully.
This also adds code to pad out any short rows, in order to be more tolerant of badly designed tables.
> Table export: Cope with tables with hidden cells

- iXBRLViewerPlugin/viewer/src/js/inspector.js
- iXBRLViewerPlugin/viewer/src/js/ixbrlviewer.js
- iXBRLViewerPlugin/viewer/src/js/viewer.js
Refactors the progress dialog shown during document load in order to ensure that progress messages are shown before the actions which they're describing.
As this has to be done via an asynchronous method (requestAnimationFrame), the progress update function needs to become asynchronous, as does anything else which needs to be able to update progress.  This includes the preProcessiXBRL plugin callback.
The only visible change from this PR should be the addition of a new progress stage during document load ("Preparing document").
> Progress framework refactor

- iXBRLViewerPlugin/viewer/src/js/inspector.js
- iXBRLViewerPlugin/viewer/src/js/inspector.test.js
This fixes a bug whereby a fact that is 0 in both current and prior period was reported as "NaN% decrease on ..."
It is now reported as "from 0 in ..."
> Fix period change NaN

- iXBRLViewerPlugin/iXBRLViewer.py
- samples/src/xbrl-invalid-tests/xbrl-invalid-test.html
iXBRL reports with empty periods were previously preventing generation of a viewer.  This change makes the generation code tolerant of reports that are invalid in this respect.
> Cope with XBRL with missing periods

- .gitignore
- Dockerfile
- package.json
- setup.py
- Fixed local build by updating substitution strings in package.json, setup.py and Dockerfile
- Add .gitignore to help cleanup the repo
- Run workiva-build-cli locally and verify that the build correctly substitutes the `0.0.0` string during the build when GIT_TAG is not set and when it is set.
**review**:
@Workiva/xmas
> XMAS-5683 - Fix local build

- iXBRLViewerPlugin/iXBRLViewer.py
- iXBRLViewerPlugin/viewer/src/html/footnote-details.html
- iXBRLViewerPlugin/viewer/src/html/inspector.html
- iXBRLViewerPlugin/viewer/src/js/fact.js
- iXBRLViewerPlugin/viewer/src/js/factset.js
- iXBRLViewerPlugin/viewer/src/js/footnote.js
- iXBRLViewerPlugin/viewer/src/js/inspector.js
- iXBRLViewerPlugin/viewer/src/js/ixnode.js
- iXBRLViewerPlugin/viewer/src/js/report.js
- iXBRLViewerPlugin/viewer/src/js/report.test.js
- iXBRLViewerPlugin/viewer/src/js/search.js
- iXBRLViewerPlugin/viewer/src/js/util.js
- iXBRLViewerPlugin/viewer/src/js/viewer.js
- iXBRLViewerPlugin/viewer/src/less/block-list.less
- iXBRLViewerPlugin/viewer/src/less/inspector.less
- samples/src/continuation/continuation.html
- tests/unit_tests/iXBRLViewerPlugin/mock_arelle.py
Add support for viewing footnotes in an iXBRL document.
When selecting a fact which has one or more footnotes, the footnotes will be listed in the "footnotes" section of the inspector.  Clicking on a footnote focus on the footnote, and the inspector will show a list of facts with which that footnote is associated.
Footnotes can also be selected directly by clicking in iXBRL view, and will be highlighted by "highlight all tags".
> Footnote support

- iXBRLViewerPlugin/viewer/src/js/search.js
- iXBRLViewerPlugin/viewer/src/js/tableExport.js
This fixes a bug whereby any search resulted in a Javascript error on the console and no search results.
Also fixes a bug that prevent table export from working. 
Both bugs introduced by footnote support.
> Fix broken search

- iXBRLViewerPlugin/viewer/src/js/inspector.js
- iXBRLViewerPlugin/viewer/src/js/viewer.js
When you first load the viewer, there is no fact selected.  Once you have clicked on a fact, there is no way to get back to the initial state of having no fact selected.
This PR makes it so that clicking on any untagged area in the viewer window will remove your current fact selection.
> Deselect fact on click away

- iXBRLViewerPlugin/iXBRLViewer.py
- iXBRLViewerPlugin/viewer/src/js/fact.js
This PR improves the display of nil-valued facts in the fact inspector.
The value is now shown as "nil", and the accuracy as "n/a", rather than a blank value and "infinite" accuracy.
Fixes #77
> Support nil-valued facts

- iXBRLViewerPlugin/viewer/src/js/viewer.js
This PR adds support for the `-sec-ix-hidden` custom style property, allowing arbitrary HTML elements to be linked to hidden facts.
Clicking on such an element in the viewer will show the details of the hidden fact with the ID that is the value of the property.  The value shown in the fact inspector will be the value from the hidden element, which may be unrelated to the text in the HTML element.
The PR also adds support for the equivalent property for ESEF, `-esef-ix-hidden`.
> Support for -sec-ix-hidden

- iXBRLViewerPlugin/viewer/src/js/inspector.js
This fixes the issue reported by @derekgengenbacher-wf whereby clicking on the graph icon causes a JavaScript error.
> Fix javascript error when clicking on graph icon

- package.json
- A recently updated dependency is requiring core-js. So it was add to package.json
- CI
**review**:
@Workiva/xt
> XT-402 - Add core-js to the dependencies

- iXBRLViewerPlugin/viewer/src/js/viewer.js
Fixes bug where viewer would fail to load if an `<ix:continuation>` element appeared within `<ix:hidden>`.
Fix is in 5697362.  
56336e2 is whitespace changes only.
> XT-491 - Hidden continuation bug

- iXBRLViewerPlugin/iXBRLViewer.py
- iXBRLViewerPlugin/viewer/src/html/inspector.html
- iXBRLViewerPlugin/viewer/src/js/calculations.js
- iXBRLViewerPlugin/viewer/src/js/fact.js
- iXBRLViewerPlugin/viewer/src/js/inspector.js
- iXBRLViewerPlugin/viewer/src/js/report.js
- iXBRLViewerPlugin/viewer/src/js/search.js
- iXBRLViewerPlugin/viewer/src/js/util.js
- iXBRLViewerPlugin/viewer/src/less/inspector.less
- samples/build-viewer.py
Add support for anchoring relationships:
* Wider and narrower concepts are shown in a new "Anchoring" section of the fact inspector.
* Labels and documentation from wider concepts are added to the search index for the facts to which they relate, so a search for the name or description of a wider concept will find related narrower facts.
* Search now allows search for element names, as well as labels.
The anchoring section of the fact inspector is only shown if there is at least one anchoring relationship in the document.
> Add support for wider narrower (anchoring) relationships

- iXBRLViewerPlugin/iXBRLViewer.py
- iXBRLViewerPlugin/viewer/src/js/report.js
This PR fixes #116 where concepts that not used in the report, but which are the source of a relationship do not get added to the concept information in the report.
In the case of wider-narrower relationships where the source (wider) concept is not used in the report, this causes an exception when building the search index.
For other relationships (calculations) where the source concept is not used in the report, the viewer will load as they are not added to the search index, but an exception would occur if and when the viewer attempts to get a label for them.
As well as fixing the failure to include the source information, this PR also makes the viewer cope more gracefully with an attempt to get a label for a non-existent concept, by returning a placeholder and logging a message on the …
> Missing concept definitions from relationship sources

- iXBRLViewerPlugin/viewer/src/js/inspector.js
When selecting fact, the viewer will update the fragment identifier in the URL of the browser.  Copying the URL and opening should open the viewer with that fact visible and selected.
This was broken by an earlier commit which caused the URL to be updated to a blank fact before the viewer had finished loading, resulting in no fact being selected.  This PR fixes that.
> Fix fact deep linking

- package.json
Reverts Workiva/ixbrl-viewer#122
This breaks the viewer at this time.
> Revert "Bump css-loader from 3.6.0 to 4.0.0"

- iXBRLViewerPlugin/viewer/src/js/inspector.js
```
ixbrlviewer.js:116 Uncaught TypeError: inspector.highlightAllTags is not a function
at ixbrlviewer.js:116
at HTMLDivElement.<anonymous> (ixbrlviewer.js:116)
at HTMLDivElement.dispatch (ixbrlviewer.js:25)
at HTMLDivElement.y.handle (ixbrlviewer.js:25)
```
**review**:
@Workiva/xt
> XT-829: fix fact highlighting

- iXBRLViewerPlugin/viewer/src/js/fact.js
- iXBRLViewerPlugin/viewer/src/js/footnote.js
- iXBRLViewerPlugin/viewer/src/js/inspector.js
Previously, nil-valued text facts would cause a JavaScript error when clicking on them.  This PR fixes this, and the value should be displayed as "nil" in the fact inspector.
Additionally, this PR applies italics consistently to "nil" (value) and "n/a" (units and accuracy) when they appear in the fact inspector, making a nil value distinct from a string value of `nil`.
Fixes XT 790
> Handle nil text facts

- iXBRLViewerPlugin/viewer/src/js/viewer.js
This PR fixes a bug whereby a very large tag appearing within a `<td>` or `<th>` element would cause the viewer to throw an exception and fail to load.
Previously we were embedding the content of the tag into a regex and checking that we had no significant characters either side of it.  This could lead to a regex that was too long for the regex engine.
This fix now manually extracts the text before and after the tag (using `indexOf` rather than a regex) and then checks that with a regex.
The document that triggered this bug is on issue #152 .
Fixes #152
> Fix for long text content appearing within table cells causing exception on document load

- iXBRLViewerPlugin/iXBRLViewer.py
- iXBRLViewerPlugin/viewer/src/js/aspect.js
- iXBRLViewerPlugin/viewer/src/js/aspect.test.js
- iXBRLViewerPlugin/viewer/src/js/chart.js
- iXBRLViewerPlugin/viewer/src/js/concept.js
- iXBRLViewerPlugin/viewer/src/js/fact.js
- iXBRLViewerPlugin/viewer/src/js/fact.test.js
- iXBRLViewerPlugin/viewer/src/js/factset.js
- iXBRLViewerPlugin/viewer/src/js/inspector.js
- iXBRLViewerPlugin/viewer/src/js/search.js
- iXBRLViewerPlugin/viewer/src/js/tableExport.js
This adds support for typed dimensions in the viewer.
Typed dimensions were previously dropped silently and would not be shown in the inspector.  It would also result in facts that differed only in typed dimension values would be treated as duplicate facts.
Typed dimension values are now shown in the inspector.  nil-valued typed dimensions are shown with a value of  `<nil>`
> Typed dimensions support

- iXBRLViewerPlugin/viewer/src/js/inspector.js
- A bug was introduced that prohibits the inspector from properly showing facts because an unused variable was not assigned at runtime. This PR removes that variable.
- Work with Derek to show that it actually works
**review**:
@Workiva/xt
> XT-1032 - Remove unused variable

- iXBRLViewerPlugin/iXBRLViewer.py
- tests/unit_tests/iXBRLViewerPlugin/test_iXBRLViewer.py
This fixes a bug whereby a fact with units that has no measures associated with it would result in a Python exception when generating a viewer.
The viewer is now created with null units, which is rendered as `<NO UNIT>`
> Fix for handling units with no measures (XT-831)

- iXBRLViewerPlugin/iXBRLViewer.py
- tests/unit_tests/iXBRLViewerPlugin/test_iXBRLViewer.py
There is a scenario in which the ixbrl viewer fails with the new typed dimension code. If a member of a dimension/member pair is left empty the code currently assumes it must be a typed dimension. This was a wrong assumption and has been updated.
CI
**review**:
@Workiva/xt
> XT-1029 - Add better conditionals so that empty members fall through

- iXBRLViewerPlugin/viewer/src/js/inspector.js
If a dimension doesn't have a label, the viewer should fallback on the element name.
This got broken by #153 which referenced an uninitialised variable.  The uninitialised variable was removed in #163, but this also removed the fallback behaviour.  This PR reintroduces the fallback with the correct value.
> Reintroduce fallback for taxonomy defined dimensions with missing labels

- iXBRLViewerPlugin/viewer/src/html/inspector.html
- iXBRLViewerPlugin/viewer/src/js/inspector.js
This PR re-instates the "no fact selected"  mask which should be shown when the viewer is first loaded (unless a fact ID is provided in the URL fragment).
> Fix "no fact selected" mask

- iXBRLViewerPlugin/viewer/src/js/inspector.js
This PR changes the wording displayed when no comparative data is shown because no fact with an earlier period exists in the report.
"No prior fact" is changed to "No prior fact in this report" to clarify that the comparative data is drawn only from the current report.
> Update "no prior fact" wording

- iXBRLViewerPlugin/viewer/src/js/fact.js
- iXBRLViewerPlugin/viewer/src/js/fact.test.js
- iXBRLViewerPlugin/viewer/src/js/inspector.test.js
- iXBRLViewerPlugin/viewer/src/js/util.js
No commas were being added when a fact value was set to infinite precision. This adjusts the code to format inf accuracy facts
| Current | Previous |
|---------|----------|
| <img width="419" alt="Screen Shot 2021-03-11 at 2 29 03 PM" src="https://user-images.githubusercontent.com/17255946/110857954-b804b480-8276-11eb-9d34-b2fd8b3b0c53.png"> |<img width="419" alt="Screen Shot 2021-03-11 at 2 29 16 PM" src="https://user-images.githubusercontent.com/17255946/110857942-b3400080-8276-11eb-8008-557eed762f84.png">  |
1. Create a doc with a fact that has a value large enough to have commas inserted
2. Set the fact accuracy to INF
3. Generate
4. Open the preview and verify that there are no commas in the fact value
5. Deploy this build
6. Regenerate
7. Open the preview and verify that there are …
> XT-1255 Format fact with commas and decimals when accuracy is inf

- iXBRLViewerPlugin/viewer/src/js/viewer.js
This PR fixes a bug whereby the next/prev buttons would not work correctly when the currently selected item had continuations, and the selection would wrap to the beginning or end of the document.
The bug can be seen on any document with a tag containing continuations: select the tag, and then press the "next tag" button in the top right.  Selection will move back to the first tag in the document, not the next tag.
> Fix next/prev tag behaviour in documents with continuations

- iXBRLViewerPlugin/viewer/src/js/concept.js
- iXBRLViewerPlugin/viewer/src/js/fact.js
- iXBRLViewerPlugin/viewer/src/js/inspector.js
- iXBRLViewerPlugin/viewer/src/js/report.js
- iXBRLViewerPlugin/viewer/src/js/report.test.js
Previously, if a concept that did not have an English label (or a label in the current viewer language, if different) was shown in the calculation section of the inspector, a blank line was shown.
This PR fixes this by changing the label language fallback to be:
1. Current viewer language
2. en
3. en-US
4. (new) Any defined label (chosen deterministically based on language code in alphabetical order)
If no label is found, the calculation view will now fall back on concept name, so a blank line is never displayed.
The above fallback hierarchy is now used in all places where a label is displayed.
Fixes XT-1354
> Avoid missing elements in calculation inspector and improve label language fallback

- iXBRLViewerPlugin/viewer/src/js/ixbrlviewer.js
- iXBRLViewerPlugin/viewer/src/js/viewer.js
- samples/src/scrollable-div/scrollable-div.html
A number of ESEF filings don't have scroll bars on the `<body>` element but instead have a `<div>` element that takes up the whole viewport and has a scrollbar.  With such documents, the viewer would not scroll the viewport to show the selected fact.
This PR fixes this, by scrolling any scrollable ancestor elements as required to make an element visible.
The PR also fixes a small bug whereby inline styles and other attributes on the `<body>` tag were not copied into the inspector's iframe.
A sample document with both inline body styles and content in a scrollable div is included.  A real world example of a document with the scrollable div problem can be seen here:
https://filings.xbrl.org/5493007JXOLJ0QCY2D70/2020-12-31/ESEF/GB/
The PR also fixes scrolling to elements where the tag is not …
> Fix scrolling to show selected elements on documents with scrollable divs

- iXBRLViewerPlugin/viewer/src/js/concept.js
- iXBRLViewerPlugin/viewer/src/js/search.js
This PR makes the viewer more tolerant of invalid iXBRL documents with missing concept definitions.
Currently, if an iXBRL report references a concept which does not exist in the taxonomy, an exception is thrown when building the search index. This fixes this.
> Tolerate missing concepts when fetching references

- iXBRLViewerPlugin/viewer/src/js/ixbrlviewer.js
- iXBRLViewerPlugin/viewer/src/less/loader.less
This PR provides some minor performance improvements to viewer loading:
* Polling interval to check if all iframes have finished rendering is increased from 10ms to 250ms
* The loading spinner animation is now much slower and uses fewer animation frames
At present these only have a modest benefit, as they only affect the time when the spinner is showing.  I have a separate set of changes in progress which make it possible for the spinner to be shown during the whole document load, and my tests show that these changes reduce load time by 15-30%.
> Loading performance improvements

- .github/dependabot.yml
The generated dependabot config wasn't setup correctly. This should fix the errors along with cleaning up the ignored dependency versions that are known to be incompatible
> XT-1450: Fix v2 dependabot config

- .github/dependabot.yml
The auth secrets aren't made available to dependabot in this repo. As an open source repo it also doesn't use any internal dependencies that would require these registries.
> XT-1468: Remove private package registries from dependabot config in open source repo

- iXBRLViewerPlugin/viewer/src/less/colours.less
This PR swaps the colors used for highlighting facts in the 2nd and 3rd namespaces used in a document.
This is for consistency with the Workiva plugin which has also swapped these colors, and is needed in order to make the "key" that appears when hovering over the "?" icon show the correct colors.
The way this currently works is somewhat fragile, as the key allocates the colors in a fixed order, and the plugin needs to make sure that it allocates the same colors in the same order to the items in the key.  There's some discussion of making the color palettes configurable which would involve giving this code an overhaul, so I think it makes sense to just do this simple fix for now.
> Swap highlight colors

- iXBRLViewerPlugin/viewer/src/js/inspector.js
This PR fixes a regression that prevents the namespace key that appears when you mouse over the question mark next to "Highlight" in the title bar from working.
With this PR, a box should appear when the mouse is over the question mark showing the colors allocated to each namespace in the document.
The regression was introduced by c837db1208d4ff460669016774e42ea8fe8c0d50
> Fix popup namespace key

- iXBRLViewerPlugin/viewer/src/js/inspector.js
- iXBRLViewerPlugin/viewer/src/js/ixbrlviewer.js
- iXBRLViewerPlugin/viewer/src/js/menu.js
This PR adds a configuration option to highlight tags by default on viewer startup.  At the moment, this option is not set in the public viewer, but it is available for plugins to call when instantiating the viewer.
> Add option to highlight tags by default

- Dockerfile
- Host the ixviewer.js on the CDN for easy download
Hit `https://cdn-dev.wdesk.org/ixbrl-viewer/<build_id>/ixbrlviewer.js` and verify that the ixviewer.js is hosted correctly on the CDN.
**review**:
@Workiva/xt
> XT-1517 - Host ixviewer.js on the CDN

- README.md
Update documentation to highlight that the ixviewer aasset can be accessed via CDN, github or built locally.
CI
**review**:
@Workiva/xt
> XT-1541 - Update the readme to call attention to the different ways the ixviewer.js can be accessed

- iXBRLViewerPlugin/iXBRLViewer.py
- iXBRLViewerPlugin/viewer/src/js/fact.js
- iXBRLViewerPlugin/viewer/src/js/fact.test.js
- iXBRLViewerPlugin/viewer/src/js/inspector.js
- samples/src/xbrl-invalid-tests/xbrl-invalid-test.html
This PR improves display of invalid iXBRL values.  For example, a formatted number such as `38,000.00` which does not have a transform specified, or a value which does not match the specified transform.
Such values now show "Invalid value" rather than "NaN"
> Improve support for invalid iXBRL values

- .github/dependabot.yml
The latest major i18next and jest versions fail the build. Make dependabot ignore those updates until the repo is updated to be compatible.
> XT-1678: Update dependabot ignore list

- iXBRLViewerPlugin/viewer/src/html/inspector.html
- iXBRLViewerPlugin/viewer/src/js/fact.js
- iXBRLViewerPlugin/viewer/src/js/footnote.js
- iXBRLViewerPlugin/viewer/src/js/inspector.js
- iXBRLViewerPlugin/viewer/src/js/report.js
- iXBRLViewerPlugin/viewer/src/js/viewer.js
- iXBRLViewerPlugin/viewer/src/less/components.less
- iXBRLViewerPlugin/viewer/src/less/inspector.less
- samples/src/continuation/continuation.html
This PR adds support for fact-explanatoryFact relationships.  These are footnote relationships between a pair of facts, rather than a fact and a footnote.  Prior to this PR, the viewer would crash when opening documents with these relationships.
Facts that are the target of footnote relationships are shown in the "Footnotes" section, alongside any text footnotes.
Facts that are the source of an inbound footnote relationship to another fact are shown in the "Associated facts" section, as they are currently in the footnote inspector.  The "associated facts" section is only shown for facts if there is at least one such inbound relationship.
This PR also fixes the highlighting of "related facts" (highlighting of other facts of in a calculation or search results) which previously only …
> fact-explanatoryFact support

- iXBRLViewerPlugin/viewer/src/js/report.js
- iXBRLViewerPlugin/viewer/src/js/viewer.js
- iXBRLViewerPlugin/viewer/src/less/inspector.less
- samples/src/ixds-test/document1.html
- samples/src/ixds-test/faurecia.html
- samples/src/ixds-test/valeo.html
This PR changes the handling of any hyperlinks in an iXBRL document in the viewer.
If viewing a document set, and the hyperlink is to a filename in the same directory, and that file is part of the current document set, the viewer will switch to the tab for that document, and scroll to the element specified by the fragment, if any.
Otherwise, the link will be opened in a new tab.
This PR also fixes a bug where the viewer pane is pushed off the bottom of the screen when the document set tab bar is visible.
> Document set cross document links / other links in new tabs

- iXBRLViewerPlugin/viewer/src/js/viewer.js
- Fixes same document hyperlinking
-  Master's behavior was that a new tab was opened and the link didn't take you to the location within the document
1. Create an ixbrl file with a link to a different location within itself (preferrably a different page so you can verify it actually scrolls)
2. Generate an ixbrl-viewer using master
a. Verify that clicking on the hyperlink opens a new tab and doesn't take you to the desired location within the doc
3. Generate an ixbrl-viewer using this branch
a. Verify that clicking on the hyperlink doesn't open a new tab and navigates you within the document
@paulwarren-wk @derekgengenbacher-wf @austinmatherne-wk
> Fix same-document links

- iXBRLViewerPlugin/viewer/src/js/inspector.js
- iXBRLViewerPlugin/viewer/src/js/viewer.js
The PR fixes and improves behaviour of the next/prev tag buttons in the presence of double-tagged facts.
Firstly, if you double tag a value which is the only content of a table cell, next/prev fact navigation would always skip over the second fact. This is now fixed, so next/prev will take you through each tag in turn.
Secondly, whenever you have double-tagged facts, clicking on the fact would show both in the inspector, but select the second (innermost) fact, meaning that "next" would take you onto a completely different fact.  This is now fixed so that it is the first fact that is selected, and "next" will take you to the second fact.   This logic is only applied for double tags (i.e. two tags with exactly the same content) not for other nested facts.
Fixes XT-1383
> Improve behaviour of next/prev tag with double tagged items

- iXBRLViewerPlugin/__init__.py
- iXBRLViewerPlugin/iXBRLViewer.py
If the viewer build was given a file that already contained an iXBRL viewer as input, it would add a second pair of `<script>` tags, leading to unpredictable results when the viewer was opened.
With this PR, the builder raises an error if given a viewer file as input.
Fixes #293
> Prevent insertion of script tags if document already contains them

- iXBRLViewerPlugin/iXBRLViewer.py
- tests/unit_tests/iXBRLViewerPlugin/test_iXBRLViewer.py
Certain input documents could cause the generated viewer to use prefixed `<script>` tags (`<xhtml:script>` rather than `<script>`).  Doing so will either cause the viewer to load completely, or the viewer will load, then fail with "Could not find viewer data") (the failure mode depends on whether the browser treats the file as HTML or XHTML).
The arrangement that triggers the bug is where the input document uses a default HTML5 namespace, but also declares a non-default prefix for that namespace, and the non-default NS declaration appears first, i.e.:
```
<html 
xmlns:xhtml="http://www.w3.org/1999/xhtml"  
xmlns="http://www.w3.org/1999/xhtml"
>
```
A real world example of this is [this filing](https://filings.xbrl.org/549300CSLHPO6Y1AZN37/2021-12-31/ESEF/SE/0/)
This PR fixes this, so that …
> Ensure that <script> tags always use default namespace (#282)

- iXBRLViewerPlugin/viewer/src/js/viewer.js
This PR fixes a bug whereby navigating to a fact did not reliably scroll to the right location.  It can be seen with this document:
https://filings.xbrl.org/5299007OWYZ6I1E46843/2021-12-31/ESEF/DK/0/
And can be seen with this direct link:
https://filings.xbrl.org/5299007OWYZ6I1E46843/2021-12-31/ESEF/DK/0/5299007OWYZ6I1E46843-2021-12-31-en/reports/ixbrlviewer.html#f-ixv-4
This selects the Revenue element, but unless you have a really tall screen, the tag will be off the top of the page (it should be in the middle).
To reproduce manually:
* Open the above document in a viewer.
* Scroll to top of document.
* Search for "Revenue"
* Double click
* Viewer will be centered on the page containing the fact, not the fact itself.
The viewer employs the following logic to focus a fact:
* Find the …
> Fix scroll-to-fact in documents with elements with overflowing content

- iXBRLViewerPlugin/viewer/src/js/viewer.js
This fixes a bug whereby next/prev tag selection did not work reliably, and "highlight XBRL elements" did not work at all on some filings with multiple target documents.
The bug is triggered when facts in the non-default target document do not have an ID attribute.  The viewer relies on all facts having ID attributes, and the viewer generator adds ID attributes for all facts, but only for the current target document (which is always the default).
It would good to add proper support for multiple target documents, but this fix makes the default target document work reliably.
The problem can be seen with this filing:
https://filings.xbrl.org/5299007OWYZ6I1E46843/2021-12-31/ESEF/DK/0/
Steps to reproduce:
* Open viewer
* No tag should be selected
* Hit "next tag"
* Nothing happens.
* Manually …
> Ignore iXBRL elements that are not in the default target document

- iXBRLViewerPlugin/viewer/src/js/fact.js
- iXBRLViewerPlugin/viewer/src/js/ixnode.js
- iXBRLViewerPlugin/viewer/src/js/outline.test.js
- iXBRLViewerPlugin/viewer/src/js/viewer.js
- samples/build-viewer.py
- samples/src/ixds-test/document1.html
Show footnotes on hidden facts
Create a viewer from this [doc](https://github.com/Workiva/ixbrl-viewer/files/8566016/footnote-on-hidden-fact.zip) . Then pull this branch locally, build the javascript and drop it into a folder with the ixbrl-viewer docs. Update the doc to point at the new javascript. Start up a simple python server from the ixbrl-viewer directory and then navigate to the html doc. Do a search for `AccumulatedDeferredInvestmentTaxCredits`. The first 7 facts should be hidden. Click through them and verify that the footnotes are shown for some of the facts. 
**review**:
@Workiva/xt
> Show footnotes on hidden facts

- iXBRLViewerPlugin/iXBRLViewer.py
- iXBRLViewerPlugin/localviewer.py
This fixes a regression in the Arelle GUI local viewer behaviour reported as #275.
To reproduce, open the Arelle GUI, enable the iXBRL viewer plugin, and check View ->iXBRL Viewer -> launch viewer on load.
Open any iXBRL report, and note the stack trace reported in the log as per #275.
With this PR, the report should open with the viewer enabled in a browser window.
The stack trace was masking two further problems:
1. Arelle in GUI mode doesn't appear to use a log buffer, so we can't get validation messages.  The PR disables showing validation messages in the viewer.
2. `localviewer.py` was using incorrect/out-of-date arguments for Arelle's `static_file` function.
Fixes #275
> Fix Arelle local viewer

- iXBRLViewerPlugin/iXBRLViewer.py
- iXBRLViewerPlugin/viewer/src/js/report.js
- iXBRLViewerPlugin/viewer/src/js/report.test.js
- tests/unit_tests/iXBRLViewerPlugin/test_iXBRLViewer.py
This PR fixes a bug where the viewer would fail to load if the taxonomy contained a `<roleDef>` element without a `<definition>` element, and the role was included in the document outline view.
[Example report with missing definition elements](https://filings.xbrl.org/391200EUISAEF39QR618/2021-12-31/ESEF/MT/0/BrownsPharmaHoldingplc-2021-12-31.zip)
This construct resulted in `null` being included in the taxonomy data as the label for the role, with a resulting error when used with [`localeCompare`](https://github.com/paulwarren-wk/ixbrl-viewer/blob/fix-null-roleDef/iXBRLViewerPlugin/viewer/src/js/outline.js#L167)
> Fix handling of roleDef with no definition

- .dockerignore
- .github/dependabot.yml
- .gitignore
- Dockerfile
- iXBRLViewerPlugin/viewer/src/less/fonts.less
- iXBRLViewerPlugin/viewer/src/less/form-controls.less
- iXBRLViewerPlugin/viewer/src/less/icons.less
- iXBRLViewerPlugin/viewer/src/less/inspector.less
- iXBRLViewerPlugin/viewer/src/less/loader.less
- iXBRLViewerPlugin/viewer/src/less/viewer.less
- package.json
Also updates stylelint which was held back because it no longer supported old node versions.
Use this [service build](https://ci.webfilings.com/build/3723532) for testing
> XT-2147: Update Node to LTS release for builds

- Dockerfile
Missed this on the prior PR because the pypi package isn't used. Still good to fix it.
Steps to test
* CI
@Workiva/xt
> Set python version in python build stage

- iXBRLViewerPlugin/__init__.py
Fixes #273 
This fixes the issue described on #273 - the "View -> iXBRL Viewer -> Launch viewer on load" option is not preserved, because the getter/setter use different names for the option.
> Fix "launch viewer on load" option in GUI

- iXBRLViewerPlugin/viewer/src/js/viewer.js
- samples/src/scrollable-div/scrollable-div.html
This PR fixes the logic used to scroll the browser window (if necessary) whenever a fact is focused (e.g. using the next/prev tag buttons, or when clicking in search results).
[This ESEF filing](https://filings.xbrl.org/R0MUWSFPU8MPRO8K5P83/2021-12-31/ESEF/FR/0/) lays out each page at 10 times its intended size, and then scales it down to the correct size using a CSS transform.  This broke the previous scroll-to-fact logic, resulting in the browser often scrolling to a different page when attempting to focus on a fact.
This PR restores the intended functionality, which is that if the target fact is already fully visible, it will be focused without scrolling.  Otherwise, the browser will scroll to put the target fact in the center of viewport.
A simpler test document is available in …
> Fix scroll-to-fact with scaled content

- iXBRLViewerPlugin/viewer/src/less/viewer.less
Correct issue with flickering button by removing padding and applying z-index so hovering over the edge doesn't cause repeated hiding and displaying of the button.
Generate an iXBRL viewer with a table ([example](https://wk-dev.wdesk.org/a/QWNjb3VudB81NjY1NDgyMjU5NTYyNDk2/doc/8b3355952b204310846a4a998d50c8a3/r/-1/v/1/sec/8b3355952b204310846a4a998d50c8a3_33?dev=true)) and confirm that hovering along the edge of the button does not cause flickering. (See video in ticket for example)
> XT-2234: Fix Export Table button flickering on initial hover

- iXBRLViewerPlugin/viewer/src/js/ixnode.js
- iXBRLViewerPlugin/viewer/src/js/viewer.js
- iXBRLViewerPlugin/viewer/src/less/viewer.less
If an `<ix:nonNumeric>` element contains absolutely positioned elements, those elements will not be highlighted by either fact selection (blue outline) or background color if "highlight all facts" is used.  Further, if the only content of the `<ix:nonNumeric>` element is absolutely positioned elements, this will lead to an outline around an empty element:
(note small square in top left of each paragraph)
This PR fixes both of these issues, by applying separate highlighting to absolutely positioned sub elements, and removing highlighting from any element with zero height.
The issue addressed is likely to become common with the introduction of block tagging on ESEF documents that have been converted from PDF, and individual lines are often absolutely positioned `<div>` elements.
The end …
> Fix highlighting of absolutely positioned elements within text tags

- iXBRLViewerPlugin/viewer/src/js/util.js
- iXBRLViewerPlugin/viewer/src/js/util.test.js
The viewer currently completely fails to open on Safari.  Any report will result in a blank screen, and an error message on the console ("Invalid regular expression: invalid group specifier name").
This PR rewrites the `formatNumber` method to remove reliance on negative look behind assertions, which are not supported on Safari.
> Fix viewer on Safari

- iXBRLViewerPlugin/viewer/src/js/ixbrlviewer.js
- iXBRLViewerPlugin/viewer/src/less/inspector.less
- iXBRLViewerPlugin/viewer/src/less/loader.less
- iXBRLViewerPlugin/viewer/webpack.common.js
This PR fixes some of the changes made in 2285634111f81c26d67d997a66259de120761a31 which replaced commas in `rgba` declarations with spaces:
```diff
-    border: 3px solid rgba(255, 255, 255, 0.1);
+    border: 3px solid rgba(255 255 255 10%);
```
This was in response to a stylelint update, which caused it to object to the `rgba(r,g,b,a)` notation, but the correct replacement is `rgb(r g b / a)` (`rgba(r g b a)` is invalid).   
Unfortunately, by default, less treats `b / a` as a pre-processed division operation, so this PR also tweaks how the less is imported so that `math: strict` is specified as a [less option](https://lesscss.org/usage/#less-options-math), which prevents less from treating `b / a` as a calculation.
Without this PR, various things are broken in the viewer:
* The gray …
> Fix rgba() declarations

- iXBRLViewerPlugin/viewer/src/js/chart.js
This PR fixes a rendering issue with the chart that causes the chart to overlap with the dimension selectors at the bottom of the dialog.
Before:
After:
This issue is that the code to allow space for the dimension selectors was picking the hidden `.other-aspects` from the dialog  template, rather than the currently displayed dialog.
> Fix display of chart

- iXBRLViewerPlugin/viewer/src/js/viewer.js
Scroll-to-fact does not work correctly on documents that are rendered in quirks mode, due to an error in obtaining the viewport height.
This can be seen whenever a fact is selected that is not already on the screen, for example:
* Using the prev/next tag buttons
* Using a fragment in the URL to deep link to a fact
* Clicking on a fact in search results
On affected documents, the viewer will not scroll as it mistakenly concludes that the fact is already visible.
Sample docs:
* [This Aviva filing](https://filings.xbrl.org/YF0Y5B0IB8SM0ZFG9G81/2021-12-31/ESEF/GB/0/) renders in quirks mode (broken without this PR).  
* [This Pandora filing](https://filings.xbrl.org/5299007OWYZ6I1E46843/2021-12-31/ESEF/DK/1/PAND-2021-12-31/) renders in standards mode and works currently.
Note that the …
> Fix scroll to fact for documents in quirks mode

- iXBRLViewerPlugin/viewer/src/js/util.js
- iXBRLViewerPlugin/viewer/src/js/util.test.js
- package.json
This PR avoids decimals with a large number of significant figures from being truncated when displayed in the fact inspector.
The last three [new tests](https://github.com/Workiva/ixbrl-viewer/compare/master...paulwarren-wk:ixbrl-viewer:big-decimal-truncation?expand=1#diff-4abe2da922e1dfef10090104939b6a0292fad5a67f35a09a27fa3528f7785e71R100) in this PR all fail under the old code.
This adds a dependency on `decimal.js`. I have another branch with draft support for Calculations 1.1 which also relies on `decimal.js`, so the new dependency will not be exclusively for this.
This fixes XT-1279
> Big decimal truncation

- iXBRLViewerPlugin/viewer/src/js/accordian.js
- iXBRLViewerPlugin/viewer/src/js/docOrderIndex.js
- iXBRLViewerPlugin/viewer/src/js/inspector.js
- iXBRLViewerPlugin/viewer/src/js/ixnode.js
- iXBRLViewerPlugin/viewer/src/js/viewer.js
This PR address a bug encountered where a document contains `ix:continuation` elements for facts or footnotes that are not in the default target document.   The viewer should ignore facts that are not in the default target document, but continuations for such elements were not being ignored (they don't have a `target` attribute so they can't be trivially ignored).  This lead to an exception when they were clicked on, or when they were selected using next/prev tag.
The bug can be seen in [this filing](https://filings.xbrl.org/5299004SWFL5JAN4W830/2022-06-30/ESEF/DK/0/5299004SWFL5JAN4W830-2022-06-30-en/reports/ixbrlviewer.html)
Open the viewer, press the "next tag" button and note that "June 30, 2022" is highlighted, but there are no fact details in the inspector, and we have an exception …
> Handle continuations for items in non-default target document

- iXBRLViewerPlugin/viewer/src/js/tableExport.js
This PR fixes an issue with table export not detecting table cells where the `<tr>` elements have `display: contents`.
The code currently searches for `tr:visible td:visible` and `display: contents` doesn't count as "visible"
For the purposes of exporting table contents, we only really care about whether the table cells themselves are visible.
> Don't require <tr> tags to be visible for table export.

- Dockerfile
The latest CI builds are failing due to a jfrog auth issue with the latest version of npm (9.1.1) and the workiva build tool.
This issue has been reported to the build team, in the meantime don't update npm to an incompatible version in docker build.
* CI build completes
> XT-2526: Fix build error

- iXBRLViewerPlugin/xhtmlserialize.py
This fixes a bug introduced in #342 that caused the content of tags in an iXBRL document to be replaced with an empty string.  We set content of tags with content of `None` to be `""` to prevent a self-closing tag being used, but due to operator precedence, this was also being inadvertently applied to tags with content, overwriting it. 
Fixes #344.
> Fix application of self-closing tags

- iXBRLViewerPlugin/viewer/src/html/inspector.html
- iXBRLViewerPlugin/viewer/src/js/ixbrlviewer.js
- iXBRLViewerPlugin/viewer/src/js/messagebox.js
- iXBRLViewerPlugin/viewer/src/js/viewer.js
- iXBRLViewerPlugin/viewer/src/less/inspector.less
This PR introduces a check on the number of continuation elements in a document, and offers to gracefully stop trying to load if there are more than 10,000.  
We now display the following dialog:
This dialog comes up fairly quickly, as the initial scan for continuation elements is fairly cheap.  
If you choose "Cancel" the loading mask is removed, but the inspector is grayed out:
This fixes #358, where a document with 70,000 continuation elements would cause the viewer to hang when loading, and would typically leave the browser tab unresponsive for several minutes.
> Show warning dialog on more than 10,000 continuation elements

- iXBRLViewerPlugin/viewer/src/js/viewer.js
This PR changes how the `ixbrl-no-highlight` class is used.  This class is added to wrapper nodes which contain only absolutely positioned children and thus have no intrinsic dimensions of their own, and should not be highlighted (their children are highlighted instead).
#363 contains a background image on an `inline-block` element, which we wrap in a `<span>`.  Despite containing the span with the image, `getBoundingClientRect()` reports a height of zero and as a result gets the `ixbrl-no-highlight` class added.  
This PR changes the behaviour so that `ixbrl-no-highlight` is never added to a span wrapper.  Despite apparently having "zero height", adding an outline to this element results in the correct area being highlighted, so this seems to be an oddity of `getBoudingClientRect()`. …
> Wrap content containing an inline-block in an inline-block

- .gitignore
- iXBRLViewerPlugin/__init__.py
- iXBRLViewerPlugin/iXBRLViewer.py
#370
- Starts logging on load (similar to edgar renderer [1](https://github.com/Arelle/EdgarRenderer/blob/60d4b56fcd2a79356724196664d2e56b5e8b1251/__init__.py#L12960), [2](https://github.com/Arelle/EdgarRenderer/blob/60d4b56fcd2a79356724196664d2e56b5e8b1251/__init__.py#L1565))
- Allows viewer to be saved after its loaded
- Run on the filing from the issue
**review**:
@Workiva/xt
@paulwarren-wk
> Fix the save viewer functionality

- iXBRLViewerPlugin/__init__.py
- setup.py
Add support for arelle's pip installed plugin architecture https://github.com/Arelle/Arelle/pull/573
Pip install this into arelle https://github.com/Arelle/Arelle/pull/573 branch and create an ixbrl-viewer
1. Pull both this and https://github.com/Arelle/Arelle/pull/573
2. from the arelle repo pip install <PATH_TO_ixbrl-viewer-repo>
3. from the arelle repo python arelleCmdLine.py -f filing.htm --save-viewer ixbrl-report-viewer.html --viewer-url https://cdn-prod.wdesk.com/ixbrl-viewer/1.1.44/ixbrlviewer.js
**review**:
@Workiva/xt
@paulwarren-wk
> Add support for arelle pip installed plugin architecture

- iXBRLViewerPlugin/viewer/src/i18n/en/currencies.json
- iXBRLViewerPlugin/viewer/src/js/identifiers.js
- iXBRLViewerPlugin/viewer/src/js/inspector.js
To provide a better display of monetary figures in the fact inspector with Ukrainian reports, and facts using Ukrainian company identifiers (EDRPOU).
The fact inspect now shows the currency symbol rather than the 3 letter code ("UAH")
The inspector will also add a "EDRPOU" prefix for for Ukrainian company identifiers (e.g. "[EDRPOU] 12345"), rather than showing them as a QName (`e:12345`)
Create an iXBRL report with a fact using units of `iso4217:UAH`  and using an entity scheme of `https://www.minfin.gov.ua`, and view the fact in the fact inspector.
**review**:
@Workiva/xt
@paulwarren-wk
> Support for Ukrainian currency symbols and company identifiers

- iXBRLViewerPlugin/iXBRLViewer.py
- iXBRLViewerPlugin/xhtmlserialize.py
- tests/unit_tests/iXBRLViewerPlugin/test_xhtmlserialize.py
At present, the XHTML produced by the viewer builder escapes `<`, `&` and `>` throughout the document.  This is fine as long as the result is treated as XHTML.   Ordinary HTML expects different escaping to `<style>` and `<script>` elements.  In particular, an escaped `>` in a style element will not be recognised as valid CSS, resulting in different rendering in HTML and XHTML rendering mode.
With this PR, the viewer does not escape `>` appearing within `<style>` elements (this is optional in XML/XHTML).
`<` and `&` are escaped as if they are appearing within a CSS string using `\NNNNNN` hex escapes (this is the only place other than comments in which they can legally appear in CSS).
This is an alternative solution for #384 .
Create an iXBRL document with an inline style sheet, and a style …
> XT-2790 Fix escaping of style element contents (add custom XHTML serializer)

- iXBRLViewerPlugin/viewer/src/js/fact.js
- iXBRLViewerPlugin/viewer/src/js/ixnode.js
- iXBRLViewerPlugin/viewer/src/js/viewer.js
Reduce viewer loading time.
This PR avoids two operations done during the pre-process iXBRL phase that trigger a reflow of the document.  On the attached test document on my laptop this reduces the pre-process phase from 18 seconds to 1 second.
* The `is(":hidden")` check, which is used to display the "concealed fact" warning in the inspector, is now done on demand.
* The check for zero-size nodes (because they contain absolutely positioned nodes) is now only done on elements that actually contain absolutely positioned nodes.  Many documents won't contain absolutely positioned content at all.  
Try opening the attached IXDS in the viewer, and note the time taken to load before and after applying this PR:
[0000078003-20-000014-xbrl …
> Improve load performance

- iXBRLViewerPlugin/viewer/src/less/viewer.less
Fixes two highlighting related issues:
1. Where a tagged element has zero size (usually because the only content is absolutely positioned elements), we add an `ixbrl-no-highlight` class to avoid putting a border around it when the fact is selected.  We previously weren't filtering on this when highlighting related facts.  For example, when mouse-overing the "associated facts" section of footnote.
2. We apply a different outline offset to table cells (-1px) from other content (+1px).  Due to a CSS priority issue, this wasn't being applied correctly when highlighting related items in a calculation:
(note green outlines are larger than blue outline)
1. Is fixed by adding `:not(.ixbrl-no-highlight)` in additional places.
2. Is fixed by adding `:not(td, th)` on the default outline offset …
> Highlighting CSS fixes

- iXBRLViewerPlugin/__init__.py
- iXBRLViewerPlugin/iXBRLViewer.py
- iXBRLViewerPlugin/localviewer.py
- iXBRLViewerPlugin/stubviewer.html
- iXBRLViewerPlugin/viewer/src/js/ixbrlviewer.js
- iXBRLViewerPlugin/viewer/src/js/report.js
- iXBRLViewerPlugin/viewer/src/js/viewer.js
- samples/build-viewer.py
To reduce the delay between opening a report and the loading mask and progress information being displayed, which can be a significant amount of time on large documents.
This change also reduces the modifications made to the source document, as no `<script>` tags are inserted.  The only  changes made to the source document are the addition of `id` attributes on any `ix` elements that don't already have them.
The change adds two new command line options:
* `--use-stub-viewer` - if specified, stub viewer mode is enabled.
* `--viewer-suffix` - a suffix that will be inserted into generated filenames.
When using stub viewer mode, the path given to `--save-viewer` should be a directory.  The viewer will output two files:
* `ixbrlviewer.html` - a small HTML file containing the `<script>` …
> Stub viewer mode

- iXBRLViewerPlugin/viewer/src/html/inspector.html
- iXBRLViewerPlugin/viewer/src/i18n/en/translation.json
- iXBRLViewerPlugin/viewer/src/js/inspector.js
- iXBRLViewerPlugin/viewer/src/js/ixbrlviewer.js
- iXBRLViewerPlugin/viewer/src/js/search.js
- iXBRLViewerPlugin/viewer/src/js/util.js
- iXBRLViewerPlugin/viewer/src/js/viewer.js
- iXBRLViewerPlugin/viewer/src/less/form-controls.less
- iXBRLViewerPlugin/viewer/src/less/inspector.less
The load process can be slow on large documents, preventing the user from interacting with the viewer.
This PR moves two slow operations into a asynchronous "post load" phase after the loading mask is removed, and the viewer becomes interactive.  These are:
* Checking for zero-size elements.  This check avoids putting an outline around empty elements.  This is slow, because it relies on the layout-triggering `getClientBoundingRect()`.  In the event that a user selects an affected fact before this operation is completed, the results is purely cosmetic, and will be fixed as soon as the worker gets to that element.
* Building the search index.  Search is now disabled until this operation is complete. 
Working with [this UBS filing](https://www.sec.gov/Archives/edgar/data/1114446/0001610520220 …
> Improve load time

- iXBRLViewerPlugin/viewer/src/html/inspector.html
- iXBRLViewerPlugin/viewer/src/js/fact.js
- iXBRLViewerPlugin/viewer/src/js/inspector.js
- iXBRLViewerPlugin/viewer/src/js/search.js
- iXBRLViewerPlugin/viewer/src/js/search.test.js
General improvements
Adds a fact value positive/negative filter
- Pull this branch
- Build the javascript
- `npm install && npm run prod`
- Create a filing with some positive an negative facts associated
- From arelle run: `python arelleCmdLine.py --plugins=/PATH_TO/ixbrl-viewer/iXBRLViewerPlugin -f /PATH_TO/filing_documents/ixbrldoc.htm  --save-viewer ixbrl-report-viewer.html --viewer-url /PATH_TO/ixbrl-viewer/iXBRLViewerPlugin/viewer/dist/ixbrlviewer.js`
- `open ixbrldoc.htm`
`--save-viewer` arg doesn't seem to be taken into account when generating a file
**review**:
@Workiva/xt
@paulwarren-wk
> XT-2866 Add ability to filter positive/negative fact values

- iXBRLViewerPlugin/viewer/src/js/viewer.js
Make the code more readable by using more modern JavaScript syntax.  See #377.
Upgrade syntax used in `viewer.js`
Depends on #401.
**review**:
@Workiva/xt
@paulwarren-wk
> Switch to class syntax, and other modern JS syntax (viewer.js)

- iXBRLViewerPlugin/viewer/src/html/inspector.html
- iXBRLViewerPlugin/viewer/src/js/fact.js
- iXBRLViewerPlugin/viewer/src/js/inspector.js
- iXBRLViewerPlugin/viewer/src/js/report.js
- iXBRLViewerPlugin/viewer/src/js/search.js
- iXBRLViewerPlugin/viewer/src/js/search.test.js
- iXBRLViewerPlugin/viewer/src/less/inspector.less
Filter facts based on their concept's status as:
- Calculation summation item
- Calculation contributing item
- Either of the above
Reworked the code that applies the filter into individual functions rather than a single if statement that will grow in complexity.
Added some helper functions to the search test code.
- CI
- Load a filing of your choosing and ensure each calculation filter works as you would expect
**review**:
@Workiva/xt
@paulwarren-wk
> XT-2867: Filter facts by calculations

- iXBRLViewerPlugin/viewer/src/html/inspector.html
- iXBRLViewerPlugin/viewer/src/js/fact.js
- iXBRLViewerPlugin/viewer/src/js/inspector.js
- iXBRLViewerPlugin/viewer/src/js/report.js
- iXBRLViewerPlugin/viewer/src/js/search.js
- iXBRLViewerPlugin/viewer/src/js/search.test.js
- iXBRLViewerPlugin/viewer/src/less/inspector.less
- Add ability to filter by extension concepts
- More generally, ability to filter by namespace is useful
- Add multi-select filter to filter facts by concept namespace.
- Only shows prefix/namespaces that are actually used by a fact in the report
- Additionally, added a filter results count to provide user with more information about their filters
- Tests have been added
- Load up a report and confirm that selecting *no* namespaces has the same number of results as selecting *all* namespaces. Confirm selecting individual namespaces works as expected.
**review**:
@Workiva/xt
@paulwarren-wk
> XT-2871: Filter facts by concept namespace

- iXBRLViewerPlugin/__init__.py
Inline XBRL Document Sets do not open in the viewer in Arelle using the View->iXBRL Viewer->Launch Viewer on load option.
Instead, there is a message in the log stating that the viewer could not be created because the target was not a directory, and the launched browser window displays a 404 error because the viewer was not generated.
This PR fixes the problem by switching to using stub viewer mode in the GUI, and passing the name of the temporary directory to the viewer builder. 
Using stub viewer mode means that the name of the viewer entry point file is trivial to predict (`ixbrlviewer.html`) but also brings the usual stub viewer advantage of reducing the delay before the loading mask is shown.
* Open Arelle GUI
* Ensure viewer plugin is loaded, and "Launch Viewer on Load" is enabled
* …
> Add support for Inline XBRL Document Sets in GUI (use Stub Viewer mode)

- iXBRLViewerPlugin/viewer/src/js/report.js
Fixes #427
Adds a guard in two places to check that item (which can be a footnote or a fact) is actually a fact before attempting to get the namespace prefix.
* Open sample doc from #427 
* Confirm that there are no errors in the log.
**review**:
@Workiva/xt
@paulwarren-wk
> Fix error trying to get a prefix for a footnote

- iXBRLViewerPlugin/viewer/src/html/inspector.html
- iXBRLViewerPlugin/viewer/src/js/fact.js
- iXBRLViewerPlugin/viewer/src/js/inspector.js
- iXBRLViewerPlugin/viewer/src/js/report.js
- iXBRLViewerPlugin/viewer/src/js/search.js
- iXBRLViewerPlugin/viewer/src/js/search.test.js
- Improves user ability to search
- The user now has the ability to filter on dimension type
- CI
**review**:
@Workiva/xt
@paulwarren-wk
> XT-2874 XT-2875 Add filter on dimension type

- iXBRLViewerPlugin/viewer/src/html/fact-details.html
- iXBRLViewerPlugin/viewer/src/html/inspector.html
- iXBRLViewerPlugin/viewer/src/i18n/en/translation.json
- iXBRLViewerPlugin/viewer/src/i18n/es/translation.json
- iXBRLViewerPlugin/viewer/src/js/inspector.js
- iXBRLViewerPlugin/viewer/src/js/search.js
- iXBRLViewerPlugin/viewer/src/js/search.test.js
- iXBRLViewerPlugin/viewer/src/less/inspector.less
- tests/puppeteer/framework/page_objects/search_panel.js
Several filters being added recently has caused the filter window to extend over the filter results through the bottom of the screen. 
- Wrap multi-select filters in collapsible sections
- Only one section can be open at a time 
- Summary of selected item(s) shown by section header when collapsed
- "x" button allows for quick clearing of an individual multi-select element
- Converted dimensions, calculations, and periods filters into collapsible multi-select filters
- Adjust dropdown filters to be inline rather than labels and dropdowns being stacked vertically
- Add `max-height` to filters window to ensure it does not hide results window if it does somehow reach 60%+ view height.
Other UI improvements in this PR that aren't necessarily related to saving UI space in filter window:
- Fact …
> XT-2959: Collapsible filter elements

- iXBRLViewerPlugin/viewer/src/js/fact.js
- iXBRLViewerPlugin/viewer/src/js/fact.test.js
The scale filter currently throws if a fact unit is null.
Don't pass an undefined measure to `this.report().qname(...)`.
1. `npm run prod`
2. Use [filing_documents.zip](https://github.com/Workiva/ixbrl-viewer/files/11748087/filing_documents.zip)
3. `python arelleCmdLine.py --plugins=/path/to/ixbrl-viewer/iXBRLViewerPlugin -f /path/to/filing_documents.zip --save-viewer ixbrl-report-viewer.html --viewer-url=/path/to/ixbrl-viewer/iXBRLViewerPlugin/viewer/dist/ixbrlviewer.js`
4. Open `ixbrl-report-viewer.html` and click into the fact and confirm that an exception isn't thrown.
**review**:
@Workiva/xt
@paulwarren-wk
> XT-2997: Handle null unit in scale filter

- Dockerfile
Builds are failing because the underlying skynet image was recently updated to use a bookworm images that causes issues with libc. We need to pin our version of python `3.9-slim` to `3.9-slim-bullseye`.
Update python image to `3.9-slim-bullseye`
CI
**review**:
@Workiva/xt
@paulwarren-wk
> XT-3016 - Update python image to 3.9-slim-bullseye

- iXBRLViewerPlugin/viewer/src/js/inspector.js
- iXBRLViewerPlugin/viewer/src/js/viewer.js
Currently, when selecting a fact, we check to see if the fact is fully visible, and if not, scroll so that is is centered in the view.
The code doesn't take into account continuations, so if you click on a continuation, and the "head" fact isn't fully in view, we scroll away from what you clicked on.  This is also a problem even without continuations if you have a large text block that is larger than the viewport.
On reflection, when you select a fact by clicking on it in the document view, I don't think it's ever desirable to scroll that view.
We now never scroll the view
See steps described on #437 (note this isn't a fix for the main part of #437, just the fact that it scrolls away from what you click on).
Alternatively, scroll so that any fact is only partially visible.  Click on it, …
> Never scroll when selecting a fact by clicking on it

- iXBRLViewerPlugin/viewer/src/html/inspector.html
- iXBRLViewerPlugin/viewer/src/js/inspector.js
- iXBRLViewerPlugin/viewer/src/less/summary.less
The new fact summary table does not work well on narrow screen widths or on documents with long prefixes.
For example, this example is from [this Japanese EDINET filing](https://disclosure2.edinet-fsa.go.jp/WEEE0040.aspx?bXVsPWNhbm94JmN0Zj1vZmYmZmxzPW9uJmxwcj1vZmYmcnByPW9mZiZvdGg9b2ZmJnBmcz02Jnllcj0mbW9uPQ==)
The long prefix names causes inconsistent column widths for the remaining width, and inconsistent wrapping of the percentage figures.
Problem is also visible with shorter prefixes on a narrow window:
This change fixes the width of the columns containing numbers, and uses diagonal column headers:
The percentage figures are forced onto a separate line, and numbers are now right-aligned.
Diagonal column headers aren't perfect, as we have to guess how much vertical space to leave (or use …
> Improve layout of tag summary table with narrow width / long prefixes

- .github/dependabot.yml
Outdated ignore list and not managing explicit Python dependencies 
Remove outdated ignore list entries and configure dependabot to manage explicit and potential future lock file dependencies.
* CI
**review**:
@Workiva/xt
@paulwarren-wk
> XT-3035 Update dependabot config

- setup.py
Workiva Deploy expects a setup.py file in pypi packages. We can delete this once we move under the Arelle org.
* Shell setup.py
* CI
**review**:
@Workiva/xt
@paulwarren-wk
> XT-3043 Create empty shell setup.py to pass Workiva Deploy validation

- iXBRLViewerPlugin/viewer/src/js/identifiers.js
- iXBRLViewerPlugin/viewer/src/js/identifiers.test.js
- iXBRLViewerPlugin/viewer/src/js/inspector.js
- iXBRLViewerPlugin/viewer/src/js/tableExport.js
- iXBRLViewerPlugin/viewer/src/js/viewer.js
Fixes #377.
Updates `inspector.js` to use ES `class` syntax, and other more modern JS constructs.  Reduces use of jQuery.
Also fixes some minor issues in the updates to `viewer.js`.
Viewer functionality should be unchanged.  Check that inspector operations work correctly as before.
**review**:
@Workiva/xt
@paulwarren-wk
> Modernize JavaScript in inspector.js

- iXBRLViewerPlugin/viewer/src/js/fact.test.js
Additional tests for the fix on #446 that more closely reflect what caused #435.  The underlying issue on #435 was calling `getScaleLabel` on a fact with absent units, rather than `null` units. 
`getScaleLabel` was previously tested via `readableAccuracy` which has its own guard for non-numeric facts, but it's also called directly from `getUsedScaleMap` on anything with a `scale` attribute.
Additional tests that call `getScaleLabel` with missing units.
Closes #435 .
**review**:
@Workiva/xt
@paulwarren-wk
> Additional test for calling getScaleLabel on facts with no units.

- .dockerignore
- Dockerfile
- README.md
Python package version detection inspects the working directory for uncommitted changes.
If there are uncommitted changes the build is determined to be a dev build. For the workiva
docker build this causes it to always be dirty because tracked files are excluded from the
build environment.
Additionally updates the Python version and includes the package lock file for the docker build.
* CI
**review**:
@Workiva/xt
@paulwarren-wk
> XT-3054 Workiva build fixes

- .github/dependabot.yml
- .github/workflows/node-tests.yml
- .github/workflows/npm-publish.yml
- .github/workflows/puppeteer.yml
- Dockerfile
We have a package-lock.json file now. We can and should use npm ci to install dependencies in CI.
We were also building and testing against [EOL Node.js versions](https://endoflife.date/nodejs).
* Use npm ci from Workiva and GitHub pipelines
* Don't use EOL Node.js versions
* ci
**review**:
@Workiva/xt
@paulwarren-wk
> XT-3064: Use npm ci

- .github/release-drafter.yml
- .github/workflows/node-tests.yml
- .github/workflows/python-tests.yml
- .github/workflows/release-drafter.yml
- .github/workflows/release.yml
Resolves #451 
* Create release drafter workflow and config
* Create release workflow (limited to manual runs until NPM and PyPI projects are transferred to Arelle user).
* CI
**review**:
@Workiva/xt
@paulwarren-wk
> XT-2854: Create release workflow

- iXBRLViewerPlugin/__init__.py
- iXBRLViewerPlugin/iXBRLViewer.py
- samples/build-viewer.py
Resolves #510 
It was determined that the most robust solution was to have the ixbrl-viewer build have access to a local copy of the script.
- Copies the script from the source path into the destination zip, directory, or the parent directory if an individual file path is provided
- Sets the `script` tag `src` attribute to the relative local path of the copied file
Generate viewers with destination as zip, directory, and file
Confirm copied script file is loaded by HTML
**review**:
@Workiva/xt
@paulwarren-wk
> XT-3086: Build viewers with reference to local copy of script

- .github/dependabot.yml
Excessive updates makes external contributions more difficult. When dependencies are added or removed. Match frequency of our other open-source repo Arelle.
Match Dependabot frequency of Arelle
* CI
**review**:
@Workiva/xt
@paulwarren-wk
> Set Dependabot update frequency to match Arelle

- README.md
- iXBRLViewerPlugin/__init__.py
- iXBRLViewerPlugin/iXBRLViewer.py
- iXBRLViewerPlugin/viewer/src/js/index.js
- iXBRLViewerPlugin/viewer/src/js/inspector.js
- iXBRLViewerPlugin/viewer/src/js/ixbrlviewer.js
- iXBRLViewerPlugin/viewer/src/js/ixbrlviewer.test.js
- iXBRLViewerPlugin/viewer/src/js/viewer.js
- samples/build-viewer.py
- tests/puppeteer/tests/highlight.test.js
- tests/unit_tests/iXBRLViewerPlugin/test_iXBRLViewer.py
Closes #519 
- Generate command line options for each feature, i.e. `--viewer-feature-review`
- Serialize enabled features in `features` array in JSON
- On load, use JSON `features` and query string to determine enablement
- Document optional features and review mode in README
- Test combinations of:
- Generating via Arelle CLI, build-viewer.py
- With  `--viewer-feature-review`, without `--viewer-feature-review`
- With `?review=true`, With `?review=false`
- Confirm expected outcome based on:
| CLI/JSON | Query Param | Result     |
|----------|-------------|------------|
| `unset`  | `unset`     | `disabled` |
| `unset`  | `true`      | `enabled`  |
| `unset`  | `false`     | `disabled` |
| `review` | `unset`     | `enabled`  |
| `review` | `true`      | `enabled`  |
| `review` | `false` …
> XT-3095: Allow enabling review feature at generation time

- iXBRLViewerPlugin/viewer/src/js/ixbrlviewer.js
- iXBRLViewerPlugin/viewer/src/js/viewer.js
Resolves #538 
Code that added `review` class to iframe body (which overrides highlighting colors) was only run when stub viewer wasn't enabled. This PR moves the addition of the `review` class alongside the review-specific untagged highlighting code.
Generate viewer with both stub viewer and review mode enabled, confirm highlighting looks as expected.
**review**:
@Arelle/arelle
@paulwarren-wk
> XT-3123: Add 'review' class separate from stub viewer logic

- iXBRLViewerPlugin/viewer/src/js/menu.js
- iXBRLViewerPlugin/viewer/src/less/menu.less
The "Download filing documents" menu option was using an HTML button.  I'm not sure if there was a reason for this, but in my view it looks out of place.  This PR re-styles it like a normal menu item.
Also fixes #541 
Changes "Download filing documents" menu option to be a normal menu item, created using well-formed XHTML.
Create a viewer from a ZIP file, such that the "download filing documents" menu item is present.  Check that the styling of the menu item is now the same as other menu items.
**review**:
@Arelle/arelle
@paulwarren-wk
> Make the download filing documents link look like a normal menu item

- iXBRLViewerPlugin/__init__.py
- iXBRLViewerPlugin/iXBRLViewer.py
The "download filing documents" feature uses the name of the ZIP file that the viewer was built from as the package to download, and copies the ZIP file into the same directory as the generated viewer.
For filings.xbrl.org, the filing already has a public URL, and we don't want to make another copy of the ZIP; we just want the download link in the viewer to link to the existing URL.
This PR provides a `--package-download-url` option.  If specified, this overrides the current logic for adding the `filingDocuments` property to the JSON, and does not attempt to take a copy of the ZIP file.
Create a viewer from the command line, and specify a URL using `--package-download-url`.  This can by absolutely any URL, but for realism a URL to a ZIP file would be most suitable.  Check that the …
> Add an option to provide URL to download filing documents.

- iXBRLViewerPlugin/viewer/src/js/inspector.js
If the current viewer is used on reports prepared for an older viewer, the information to populate the file summary section is not present, leading to an empty section header:
This removes the section entirely if it is empty.
* Either: Build a viewer using a release older than 1.1.68, then copy ixbrlviewer.js built from this PR in place of the older one.  
* Or: build a viewer using this PR, and then manually delete the `localDocs` property from the JSON data.
* Check that there "File Summary" heading is completely absent, rather than empty
**review**:
@Arelle/arelle
@paulwarren-wk
> Hide file summary if no files present.

- iXBRLViewerPlugin/__init__.py
- iXBRLViewerPlugin/constants.py
- iXBRLViewerPlugin/featureConfig.py
- iXBRLViewerPlugin/iXBRLViewer.py
- iXBRLViewerPlugin/ui.py
- samples/build-viewer.py
*Recommend reviewing by commit!*
Closes #520 
- Implemented `FeatureConfig` which can be used to easily add additional features going forward
- Fixed "Load on launch" setting which hasn't been working since [this commit](https://github.com/Arelle/w-ixbrl-viewer). The setting was not being checked causing Arelle to *always* launch on load.
- Split save dialog into two separate dialogs:
- Save dialog: for saving a viewer instance, initialized with default values from config but doesn't overwrite them
- Settings dialog: for saving default settings that populate the save dialog and are used by launch-on-load
- Moved "launch-on-load" toggle from View menu to new Settings dialog
- Configured launch-on-load to generate viewer using configured settings (features and script URL)
- Generate viewers …
> XT-3096: Integrate viewer url and feature options into the tools menu

- iXBRLViewerPlugin/viewer/src/js/ixnode.js
- iXBRLViewerPlugin/viewer/src/js/util.js
Some preparers make the contents of iXBRL tags invisible, so that the visual appearance of the fact can be provided by different HTML elements.  The viewer currently detects where this is done using `display: none` and puts a "concealed fact" tag in the inspector.  We've recently discovered preparers doing the same thing, but using a transparent font color for the tag.
This is poor tagging practice, as it removes the connection between the tagged and displayed values, and interferes with the behaviour of viewers.
This PR extends the check for concealed facts to include facts with a transparent font (which we define as an alpha value of less than 10%).
Create a viewer for [this filing](https://filings.xbrl.org/213800O3Z6ZSDBAKG321/2022-12-31/ESEF/HR/2/granoliogroup-2022-12-31-en.zip)
Do a …
> Show "Concealed fact" tag on transparent facts

- iXBRLViewerPlugin/viewer/src/js/viewer.js
Fixes #561.  Documents with a very large number of nodes  (140,000 in this example) within an `ix:nonNumeric` trigger a stack overflow within jQuery during document load.
This replaces the following jQuery:
```
nodes.find("*").addBack().filter(...)
```
with equivalent pure JS.  This avoids a [known issue](https://github.com/jquery/jquery/issues/3704) with the above jQuery.
Confirm that the sample on #561 now opens correctly.
**review**:
@Arelle/arelle
@paulwarren-wk
> Fix stack overflow on tags with many children

- iXBRLViewerPlugin/iXBRLViewer.py
- tests/unit_tests/iXBRLViewerPlugin/test_iXBRLViewer.py
IXDS viewer currently includes all referenced docs, including schemas. At runtime this generates tabs for all of the inline docs and referenced schemas (this can also cause an exception to be raised depending on how the viewer is hosted):
Additionally, the fake "_IXDS" doc is included as a local doc. This causes it to be included in the file summary:
* Only include referenced inline docs in docset.
* Filter out fake IXDS doc from local docs.
1. `mkdir viewer-out`
1. `python arelleCmdLine.py --plugins 'iXBRLViewerPlugin|inlineXbrlDocumentSet|transforms/SEC' --file '[{"ixds":[{"file":"filing_documents.zip"}]}]' --save-viewer viewer-out`
1. `python -m http.server --directory viewer-out`
1. open http://localhost:8000/avkr-20230630.htm and confirm tabs for `avkr-20230630.htm` and …
> IXDS bug fixes

- iXBRLViewerPlugin/iXBRLViewer.py
- tests/unit_tests/iXBRLViewerPlugin/mock_arelle.py
Related to #581, some type hints were using wrong (or missing) imports causing a consuming application to raise type hint errors.
* Use ModelXbrl class instead of module as type hint.
* Replace `List` type hint (with missing import from typing) with `list` type.
* CI
**review**:
@Arelle/arelle
@paulwarren-wk
> Fix some incorrect type hints

- iXBRLViewerPlugin/viewer/src/js/chart.js
report changed from a function to a field of the Fact class in #568 
Resolves `Uncaught TypeError: e.report is not a function` exception when opening one of the analyze diagrams.
Click the analyze button on a fact:
**review**:
@Arelle/arelle
@paulwarren-wk
> Fix reports fact reference

- iXBRLViewerPlugin/viewer/src/js/docOrderIndex.js
- iXBRLViewerPlugin/viewer/src/js/inspector.js
- iXBRLViewerPlugin/viewer/src/js/inspector.test.js
- iXBRLViewerPlugin/viewer/src/js/reportset.js
- iXBRLViewerPlugin/viewer/src/js/util.js
- iXBRLViewerPlugin/viewer/src/js/util.test.js
- iXBRLViewerPlugin/viewer/src/js/viewer.js
- The `SHOW_FACT` event was passing legacy fact IDs to `selectItem`
- Handling of SEC/ESEF links-to-hidden IDs was not using VUIDs
Fix above cases where VUIDs were not being used, and do widespread renaming of `id` => `vuid` for clarity of where VUIDs are expected.
CI
**review**:
@Arelle/arelle
@paulwarren-wk
> Update legacy/VUID fact ID usage for SHOW_FACT and SEC/ESEF hidden facts

- iXBRLViewerPlugin/__init__.py
Uses the aliases field introduced in Arelle/Arelle/pull/958 to support calling the plugin by both the name (`ixbrl-viewer`) and the prior plugin path (`iXBRLViewerPlugin`) when pip installed.
Add `iXBRLViewerPlugin` plugin alias
local pip install and call the plugin using both the name (`ixbrl-viewer`) and alias (`iXBRLViewerPlugin`).
* `python arelleCmdLine.py --plugins iXBRLViewerPlugin --save-viewer ixbrl-viewer.htm --file https://filings.xbrl.org/529900FSU45YYVLKB451/2023-09-30/ESEF/DK/0/529900FSU45YYVLKB451-2023-09-30-EN.zip`
* `python arelleCmdLine.py --plugins ixbrl-viewer --save-viewer ixbrl-viewer.htm --file https://filings.xbrl.org/529900FSU45YYVLKB451/2023-09-30/ESEF/DK/0/529900FSU45YYVLKB451-2023-09-30-EN.zip`
**review**:
@Arelle/arelle
@paulwarren-wk
> Add `iXBRLViewerPlugin` plugin alias

- iXBRLViewerPlugin/viewer/src/js/aspect.js
- iXBRLViewerPlugin/viewer/src/js/aspect.test.js
- iXBRLViewerPlugin/viewer/src/js/chart.js
- iXBRLViewerPlugin/viewer/src/js/chart.test.js
- iXBRLViewerPlugin/viewer/src/js/concept.test.js
- iXBRLViewerPlugin/viewer/src/js/fact.js
- iXBRLViewerPlugin/viewer/src/js/fact.test.js
- iXBRLViewerPlugin/viewer/src/js/factset.test.js
- iXBRLViewerPlugin/viewer/src/js/inspector.test.js
- iXBRLViewerPlugin/viewer/src/js/outline.test.js
- iXBRLViewerPlugin/viewer/src/js/report.js
- iXBRLViewerPlugin/viewer/src/js/report.test.js
- iXBRLViewerPlugin/viewer/src/js/reportset.test.js
- iXBRLViewerPlugin/viewer/src/js/unit.js
- iXBRLViewerPlugin/viewer/src/js/unit.test.js
- iXBRLViewerPlugin/viewer/src/js/util.js
- jest.config.json
- package.json
Resolves #575
Replaces the use of `measureLabel` (which simply took the first numerator of a complex unit for displaying a label) with `unitLabel`, which transforms simple or complex units into title-cased, more human-readable labels with currency symbols where applicable.
Use example doc in linked issue to confirm complex units show completely and correctly:
**review**:
@Arelle/arelle
@paulwarren-wk
> Display complex units correctly

- .github/workflows/python-tests.yml
- .gitignore
- pyproject.toml
- setup.cfg
- tox.ini
Resolves #581
Adds mypy type-checking, flake8 linting, and nose2 unit testing via CI via tox.
mypy and flake8 are initially configured to ignore existing failures, future changes can correct those failures while removing the associated ignore configuration.
CI
**review**:
@Arelle/arelle
@paulwarren-wk
> Add mypy, flake8, and nose2 tests to CI via tox

- .github/workflows/python-tests.yml
- pyproject.toml
The `ixbrl-viewer` python package is most often used in tandem with Arelle source or some other Arelle installation. Having `arelle-release` as a dependency of `ixbrl-viewer` causes an additional version of Arelle to be installed in `site-packages`.
This is likely a precedent for other non-built-in Arelle plugins going forward, so discussion on alternatives is encouraged.
Move `arelle-release` dependency to optional `arelle` dependencies group.
CI
**review**:
@Arelle/arelle
@paulwarren-wk
> Make arelle-release dependency optional

- ARCHITECTURE.md
- iXBRLViewerPlugin/iXBRLViewer.py
- iXBRLViewerPlugin/viewer/src/html/inspector.html
- iXBRLViewerPlugin/viewer/src/i18n/en/translation.json
- iXBRLViewerPlugin/viewer/src/i18n/es/translation.json
- iXBRLViewerPlugin/viewer/src/js/inspector.js
- iXBRLViewerPlugin/viewer/src/js/util.js
- iXBRLViewerPlugin/viewer/src/js/viewer.js
- tests/unit_tests/iXBRLViewerPlugin/test_iXBRLViewer.py
To support an XBRL feature used by a growing number of jurisdictions
The viewer builder will now include all target documents that have been loaded by Arelle, and the viewer no longer ignores non-default target documents when pre-processing.
The key changes on the builder side are to create a single "source report" for a given set iXBRL document set, and to change where we do the `deepcopy` of the XML document in order to ensure that the addition of missing ID attributes for all targets make it into the output.
This PR also:
* Fixes namespace highlighting if there are more than three namespaces
* Changes the search results count to refer to "facts" rather than "concepts"
Create a viewer for any document with multiple target documents.  For example, this filing: …
> Multi target document support

- .github/workflows/node-tests.yml
- .github/workflows/puppeteer.yml
- .github/workflows/python-package.yml
- .github/workflows/python-tests.yml
- Makefile
- README.md
- iXBRLViewerPlugin/__init__.py
- pyproject.toml
- tests/unit_tests/iXBRLViewerPlugin/mock_arelle.py
- tests/unit_tests/iXBRLViewerPlugin/test_iXBRLViewer.py
- tests/unit_tests/iXBRLViewerPlugin/test_xhtmlserialize.py
- tox.ini
resolves #551 
* Run CI with Python 3.12.
* Minor changes to resolve Python 3.12 warnings.
* Permit manually running CI tests via workflow dispatch.
* Migrate Python tests from nose to pytest to align with our other repos.
* Disable type checking Python test modules.
* CI (tests will fail until Arelle/Arelle/pull/1023 is merged and released).
**review**:
@Arelle/arelle
@paulwarren-wk
> Python 3.12 Support

- .github/workflows/node-tests.yml
- .github/workflows/puppeteer.yml
- iXBRLViewerPlugin/__init__.py
- iXBRLViewerPlugin/constants.py
- iXBRLViewerPlugin/iXBRLViewer.py
- iXBRLViewerPlugin/ui.py
- iXBRLViewerPlugin/viewer/src/js/viewer.js
- iXBRLViewerPlugin/viewer/src/less/common.less
- iXBRLViewerPlugin/viewer/src/less/inspector.less
- iXBRLViewerPlugin/viewer/src/less/viewer.less
- samples/build-viewer.py
Fact highlighting of absolutely positioned content doesn't apply to facts within tables. Additionally, the highlight outline width is set to a pixel size and doesn't adjust for documents that use CSS scale transforms.
* Use em sizes to define fact highlight outlines for scaled documents.
* Highlight fact content that is absolutely positioned within tables.
* Fix `AttributeError: 'IXBRLViewerBuilderError' object has no attribute 'message'`
* Use a default empty string script path (for the built-in script file) in the GUI instead of an absolute path so users can have multiple versions of Arelle and ixbrl-viewer (frozen build and Python source) on the same machine.
* Explicitly exit generation early if destination is None.
* Replace nonexistent `os.path.filepart` method reference.
* Update …
> Highlight scaled and absolutely positioned facts within tables

- iXBRLViewerPlugin/iXBRLViewer.py
Fixes #612
If an enumeration value is syntactically invalid, don't attempt to treat it is a QName, but instead set the `err` property on the fact data, so that "invalid value" is displayed in the fact inspector.
Test document on #612.
* Viewer can now be created without error for this document.
* Check both `DerivativeAssetStatementOfFinancialPositionExtensibleEnumeration` facts:
* First should say "invalid value"
* Second should work correctly, and display a label from the taxonomy.
**review**:
@Arelle/arelle
@paulwarren-wk
> Tolerate invalid enumeration values

- iXBRLViewerPlugin/__init__.py
- iXBRLViewerPlugin/constants.py
- iXBRLViewerPlugin/iXBRLViewer.py
- iXBRLViewerPlugin/ui.py
- iXBRLViewerPlugin/xhtmlserialize.py
- tests/puppeteer/tools/generate.sh
Resolves #617 
* Download and copy script into output directory if it's an http URL.
* Log an error and abort generation if script is to a file that doesn't exist or can't be downloaded.
* Add new `--viewer-no-copy-script` (also available in the GUI) option to skip copying or validating `--viewer-url` and trust the user to provide a valid script location.
* Don't open local viewer if generation failed.
* Include standard message codes on all Arelle logs.
* Fix a variable typo.
* Test valid and invalid script URLs from both the GUI and CLI with and without the copy script option.
**review**:
@Arelle/arelle
@paulwarren-wk
> Log error and abort generation if viewer script does not exist

- iXBRLViewerPlugin/viewer/src/i18n/en/translation.json
- iXBRLViewerPlugin/viewer/src/i18n/es/translation.json
- iXBRLViewerPlugin/viewer/src/js/inspector.js
The Calculation v1.1 mode switch was previously in the "highlight"  section of the top bar.  This seems wrong, as it doesn't really relate to highlighting, and it also seems unduly prominent for such an option.
The Calculation v1.1 mode switch is relocated to the existing options menu:
Open any report, and confirm that the Calculation v1.1 option is now on the options menu.
Changing this option will automatically update the fact inspector, although for most calculations this will have no visible impact.
Clicking the "details" link  on a calculation will open the calculation inspector, which will show the additional interval columns in Calculation v1.1 mode.
**review**:
@Arelle/arelle
@paulwarren-wk
> Move calculations mode option to options menu

- iXBRLViewerPlugin/iXBRLViewer.py
- iXBRLViewerPlugin/viewer/src/html/inspector.html
- iXBRLViewerPlugin/viewer/src/js/fact.js
- iXBRLViewerPlugin/viewer/src/js/inspector.js
- iXBRLViewerPlugin/viewer/src/js/report.js
- iXBRLViewerPlugin/viewer/src/less/block-list.less
- iXBRLViewerPlugin/viewer/src/less/components.less
- iXBRLViewerPlugin/viewer/src/less/inspector.less
- tests/unit_tests/iXBRLViewerPlugin/test_iXBRLViewer.py
The viewer will load facts from multiple target documents, but does not show which facts come from with target document.
Facts from a non-default target document are now tagged as such in search results and the fact inspector:
Search:
Target document information was not previously included in the report data, so new JS running on old reports will not show target document information.
Load a document with at least one non-default target document, and check that the target document is indicated in search results and the fact inspector.
**review**:
@Arelle/arelle
@paulwarren-wk
> Display the target document of facts in inspector and search

- iXBRLViewerPlugin/viewer/src/html/inspector.html
- iXBRLViewerPlugin/viewer/src/i18n/en/translation.json
- iXBRLViewerPlugin/viewer/src/js/inspector.js
- iXBRLViewerPlugin/viewer/src/js/reportset.js
- iXBRLViewerPlugin/viewer/src/js/search.js
- iXBRLViewerPlugin/viewer/src/js/search.test.js
- iXBRLViewerPlugin/viewer/src/less/inspector.less
Allows users to limit searches to specific target documents in multi-target documents.
Adds a "target documents" filter to the search filters:  
This is only shown if there is at least one non-default target document used in the report.
Open a report with a single, default document.  Click on search, then the filters icon, confirm that "Target Documents" filter is not shown.
Open a report with multiple target documents (e.g. Danish ESEF filings).  Confirm that "Target Documents" filter is now shown, and that the relevant facts are shown in the results when selected.
**review**:
@Arelle/arelle
@paulwarren-wk
> Target document search filter

- iXBRLViewerPlugin/iXBRLViewer.py
- iXBRLViewerPlugin/viewer/src/js/inspector.js
- iXBRLViewerPlugin/viewer/src/js/report.test.js
- iXBRLViewerPlugin/viewer/src/js/reportset.js
- iXBRLViewerPlugin/viewer/src/js/reportset.test.js
- pyproject.toml
Use built-in JS support for multi-lingual labels for languages, rather than including them in the viewer JSON.
Fixes #573
We currently include names for languages as part of the viewer JSON and only include them in a single language.  This means that they're not translated as part of the i18n support.
Modern JS provides `Intl.DisplayNames` which can give us language labels in different languages.
Get labels for languages using `Intl.DisplayNames`.
No longer include `languages` in the taxonomy data object.
New viewers will ignore the `languages` object if present.
Open a viewer, check the list of languages shown on the settings menu.  They should be displayed in the language  of the current locale, but this can be overridden by specifying `?lang=XX` as a query param, where `XX` is a …
> Switch to using Intl.DisplayNames

- iXBRLViewerPlugin/viewer/src/js/fact.js
- iXBRLViewerPlugin/viewer/src/js/fact.test.js
Ideally, text block facts should always be parsed and rendered as HTML, and non-text-block concept types should always be rendered literally.  We correctly only show rendered HTML for text block facts, but we incorrectly unescape non-text-block values when rendering the value inline.
The readable value of a fact should be based on whether it's a text block, not whether it's escaped.
The facts in [p-2024-03-14-en.zip](https://github.com/Arelle/ixbrl-viewer/files/14603455/p-2024-03-14-en.zip) are using `stringItemType` and should be rendered as `a&amp;b` and `c&amp;d`, not `a&b` and `c&d`.
**review**:
@Arelle/arelle
@paulwarren-wk
> Show escaped values for non-textblock facts

- iXBRLViewerPlugin/viewer/src/js/ixnode.js
- iXBRLViewerPlugin/viewer/src/js/viewer.js
For elements that only have absolutely positioned children, don't attempt to navigate to them using next/prev buttons, and ignore the fact that they're not visible when detecting concealed tags.
Fixes #647 
Also fixes a related problem with next/prev navigation not working.
When deciding whether a fact is "concealed", or when navigating to a fact, ignore wrapper nodes that have the `ixbrl-no-highlight` class.  This indicates that they have zero size, and they may be rendered in a different location to the fact itself.
Using [this document](https://filings.xbrl.org/filing/2221005IWV4R4EP4D553-2023-12-31-ESEF-IT-0), select any table tag, and confirm that it is not considered to be a "concealed tag".   Also confirm that navigating to facts (e.g. by search selection, or next/prev) works …
> Ignore absolutely-positioned content containers

- iXBRLViewerPlugin/__init__.py
Using the plugin from the Arelle Python API means not having access to command line argument defaults. It would be nice to not have to provide `viewerURL` in `RuntimeOptions` and have the default value take its place.
Fairly straight forward change, but if you're curious to test it you can construct a `RuntimeOptions` instance:
```
RuntimeOptions(
entrypointFile=str(target_path),
keepOpen=True,
pluginOptions={
'saveViewerDest': str(viewer_path),
},
plugins='ixbrl-viewer',
)
``` 
and pass it into `CntlrCmdLine`
**review**:
@Arelle/arelle
@paulwarren-wk
> Default value for `viewerURL` when using Arelle Python API

- iXBRLViewerPlugin/viewer/src/js/number-matcher.js
In review mode, untagged number highlighting was missing numbers prefixed with `[` or suffixed with `]`.
Add `[` and `]` to guard regex.
Before:
After:
**review**:
@Arelle/arelle
@paulwarren-wk
> Add square brackets to untagged number matching guards

- iXBRLViewerPlugin/iXBRLViewer.py
- iXBRLViewerPlugin/viewer/src/html/inspector.html
- iXBRLViewerPlugin/viewer/src/i18n/en/translation.json
- iXBRLViewerPlugin/viewer/src/i18n/es/translation.json
- iXBRLViewerPlugin/viewer/src/js/inspector.js
- iXBRLViewerPlugin/viewer/src/js/report.js
- iXBRLViewerPlugin/viewer/src/js/report.test.js
- iXBRLViewerPlugin/viewer/src/js/reportset.js
- iXBRLViewerPlugin/viewer/src/js/reportset.test.js
- iXBRLViewerPlugin/viewer/src/js/summary.js
- iXBRLViewerPlugin/viewer/src/js/summary.test.js
- tests/unit_tests/iXBRLViewerPlugin/test_iXBRLViewer.py
To allow for more prominent display of software credits associated with a filing that would otherwise be only visible in comments.
- For each report, retrieve software vendor names from each associated document and store in `softwareCredits` within corresponding JSON object
- When rendering a report summary, display each software vendor name under "Report Creation" section
Example filing with single name match: 
[credittest_name_match.zip](https://github.com/Arelle/ixbrl-viewer/files/15410350/credittest_name_match.zip)
Example filing with multiple pattern matches:
[credittest_pattern_match.zip](https://github.com/Arelle/ixbrl-viewer/files/15410354/credittest_pattern_match.zip)
**review**:
@Arelle/arelle
@paulwarren-wk
> Display extracted software vendor names in summary panel

- iXBRLViewerPlugin/iXBRLViewer.py
- iXBRLViewerPlugin/viewer/src/i18n/en/translation.json
- iXBRLViewerPlugin/viewer/src/js/calculation.js
- iXBRLViewerPlugin/viewer/src/js/inspector.js
- iXBRLViewerPlugin/viewer/src/js/util.js
Although we already have a mode for applying Calc 1.1 semantics to legacy calculation relationships, reports using Calculation 1.1 relationships in the taxonomy did not show any calculation relationships in the viewer.
Calculations 1.1 relationships are now included in the JSON taxonomy data.  The viewer will now show calculations defined using either relationship type, but if a total has both types in a single ELR, Calc 1.1 takes precedence.
Prepare a report using the Calc 1.1 summation-item relationship, and confirm that calculations are shown in the viewer.  Example below is a filing that has been modified to use the the new arcrole:
[wk-calc11.zip](https://github.com/Arelle/ixbrl-viewer/files/15491364/wk-calc11.zip)
**review**:
@Arelle/arelle
@paulwarren-wk
> Support for Calculation 1.1 relationships

- iXBRLViewerPlugin/__init__.py
- iXBRLViewerPlugin/iXBRLViewer.py
If the iXBRL plugin is enabled and a non-iXBRL report is loaded an exception is thrown.
```
[viewer:exception] Exception 'ModelFact' object has no attribute 'format' 
Traceback ['  File "/Applications/Arelle.app/Contents/MacOS/plugin/iXBRLViewerPlugin/__init__.py", line 119, in processModel\n    pluginData(cntlr).builder.processModel(modelXbrl)\n', '  File "/Applications/Arelle.app/Contents/MacOS/plugin/iXBRLViewerPlugin/iXBRLViewer.py", line 412, in processModel\n    self.addFact(report, f)\n', '  File "/Applications/Arelle.app/Contents/MacOS/plugin/iXBRLViewerPlugin/iXBRLViewer.py", line 282, in addFact\n    if f.format is not None:\n       ^^^^^^^^\n']
```
Check that the report is iXBRL before processing.
* Load non-iXBRL doc: `python arelleCmdLine.py --plugins ixbrl-viewer …
> Don't Process Non-iXBRL Models

- iXBRLViewerPlugin/viewer/src/js/calculationInspector.js
The calculation inspector incorrectly states that inconsistent calculations are consistent.
Switch to using correct message.
Find a document with an inconsistent calculation. Enable calc 1.1 calculation checking, open inspector for calculation and check message.
**review**:
@Arelle/arelle
@paulwarren-wk
> Fix incorrect message shown for inconsistent calculations

- iXBRLViewerPlugin/viewer/src/js/inspector.js
Fixes regression with link to contributing items in a calculation.
Clicking on a contributing item in the calculations section of the fact inspector gives an exception:
> inspector.js:772 Uncaught TypeError: Cannot read properties of undefined (reading 'vuid')
`items` changed from a property to a method, but this reference was not updated.
Open a report with calculations. Click on the calculation total, then on one of the contributing items in the fact inspector.  The contributing item should now be selected.
**review**:
@Arelle/arelle
@paulwarren-wk
> Fix links to calculation contributing items

- iXBRLViewerPlugin/iXBRLViewer.py
- tests/unit_tests/iXBRLViewerPlugin/test_iXBRLViewer.py
> https://github.com/Arelle/ixbrl-viewer/issues/683
Now all non-report pagkages files from the reports directory are copied for  the iXBRL viewer's use.
Creating a viewer with the document attached to the issue will create a viewer with integrated pictures.
**review**:
@Arelle/arelle
@paulwarren-wk
> Copying asset files from reports directory

- iXBRLViewerPlugin/iXBRLViewer.py
Resolves [google group issue](https://groups.google.com/g/arelle-users/c/KzAvo0waE2I)
The wrong constant was used from Arelle for calc 1.1.
* Generate a viewer for [a report with calc 1.1 relationships](https://github.com/user-attachments/files/17166221/ex-2024-09-27-en.calc1.1.zip).
* Verify calc 1.1 relationships show up in the inspector.
**review**:
@Arelle/arelle
@paulwarren-wk
> Use correct calc1.1 arcrole

- .github/workflows/python-tests.yml
- pyproject.toml
- tox.ini
Python 3.8 is EOL.
* Drop Python 3.8 from CI testing.
* Drop Python 3.8 support from Python package.
* CI
**review**:
@Arelle/arelle
@paulwarren-wk
> Drop support for EOL Python 3.8

- iXBRLViewerPlugin/viewer/src/js/util.js
- iXBRLViewerPlugin/viewer/src/js/util.test.js
A [Hidden Fact CSS link](https://www.xbrl.org/WGN/html-for-ixbrl-wgn/WGN-2024-11-05/html-for-ixbrl-wgn-2024-11-05.html#sec-hidden-fact-css-link) section was added to Designing HTML for Inline XBRL 1.0 that recommends `-ix-hidden`.
Update the regex and tests.
**review**:
@Arelle/arelle
@paulwarren-wk
> Support -ix-hidden

- iXBRLViewerPlugin/viewer/src/js/viewer.js
See #761
Use wrapper nodes for HTML elements that are linked to hidden facts using the `-sec-ix-hidden`/`-esef-ix-hidden` mechanism so that they are highlighted correctly.
Create a report that uses an HTML element other than `<div>` or `<span>` linked to a hidden fact using `-sec-ix-hidden` or `-esef-ix-hidden` and confirm that element has a border when selected (see example on #761).
**review**:
@Arelle/arelle
@paulwarren-wk
> Use wrapper nodes for HTML elements using hidden linked fact

- .github/workflows/node-tests.yml
- .github/workflows/puppeteer.yml
- .github/workflows/python-tests.yml
Release workflow is failing because it doesn't have contents permissions and it calls the test workflows which require it. The read permissions are not needed for workflows in open-source repo.
Remove read permissions from the test workflows.
* CI
**review**:
@Arelle/arelle
@paulwarren-wk
> Remove read contents permissions

- iXBRLViewerPlugin/viewer/src/js/inspector.js
- iXBRLViewerPlugin/viewer/src/less/inspector.less
Combination of home link and default logo clutters the top bar.  The home link should replace the logo, if enabled.
Deploy viewer with this `ixbrlviewer.config.json` config:
```json
{
"features": {
"home_link_url": "https://www.arelle.org",
"home_link_text": "My Viewer"
}
}
```
**review**:
@Arelle/arelle
@paulwarren-wk
> Remove default logo if home link feature is set

- iXBRLViewerPlugin/__init__.py
- iXBRLViewerPlugin/constants.py
Resolves exception [reported to Arelle users google group](https://groups.google.com/g/arelle-users/c/OrpdWDq_uvw). The save menu wasn't updated when the viewer was updated to use the plugin data pattern.
Also adds the new highlight_facts_on_startup and search_on_startup options options to the GUI settings menu.
* Update save menu code to use plugin data.
* Enable new features in GUI.
* CI
**review**:
@Arelle/arelle
@paulwarren-wk
> Fix GUI Save Viewer Exception

- iXBRLViewerPlugin/viewer/src/less/colours-dark-mode.less
- iXBRLViewerPlugin/viewer/src/less/colours.less
- tests/puppeteer/framework/page_objects/doc_frame.js
Highlight colors couldn't be distinguished by color blind users. This can be tested with [Colorblindly](https://github.com/oftheheadland/Colorblindly).
Before:
After:
Modified colors for accessibility.
* CI
**review**:
@Arelle/arelle
@paulwarren-wk
> Improve Accessibility of Highlight Colors

- iXBRLViewerPlugin/viewer/src/js/theme.js
- iXBRLViewerPlugin/viewer/src/js/util.js
We allow users to toggle between light and dark mode, but their choice is reset on refresh or when a different viewer is opened.
* If a user explicitly changes the theme we record their choice in local storage.
* At startup we check if a choice from a previous session is in local storage. If there is, we use it.
* CI
**review**:
@Arelle/arelle
@paulwarren-wk
> Persist User Theme Selection in Local Storage

- iXBRLViewerPlugin/viewer/src/js/inspector.js
- iXBRLViewerPlugin/viewer/src/js/reportset.js
The option for Calculations 1.1 is a bit confusing to the uninitiated, particularly if the report has no calculations at all.
Calculations 1.1 option is hidden if the document contains no calculation relationships.
Confirm that option is present for documents with calculations (e.g. ESEF/SEC) and absent on those without (e.g. CH).
**review**:
@Arelle/arelle
@paulwarren-wk
> Hide calculation mode option if document has no calculations

- iXBRLViewerPlugin/viewer/src/less/inspector.less
Regression  - no longer possible to resize the fact inspector by dragging the border between the inspector and viewer panes.
Increase the `z-order` of the viewer pane. The resize relies on an invisible HTML element that overlaps the inspector pane by a few pixels. The regression occurred in e452daaf6a48cd8ac6af0e89b6b70cddca1f53ae which swapped the order of the viewer and inspector panes to make the tab order more intuitive. Unfortunately, this meant that overlapping element was now under the inspector pane and thus inaccessible. 
Confirm that the pane can now be resized.
**review**:
@Arelle/arelle
@paulwarren-wk
> Fix inspector resize

- iXBRLViewerPlugin/iXBRLViewer.py
- tests/puppeteer/framework/page_objects/fact_details_panel.js
Fixes #793 
When adding facts to the viewer, we add an ID attribute if there isn't one already, modifying the original XML model. After processing each target document, we add a copy of the associated XML document to the viewer for serialisation. Previously, if the same document got added twice, we ignored the second one, meaning that any IDs added by the second target got lost. This PR changes this behaviour to take the latest document, which will have IDs added by all targets.
Test viewer generation with a document containing multiple target documents, and at least some facts in each document with no ID attributes. Go to search, and confirm that with no filters the number of facts shown matches the total number of facts. Confirm that filtering to each target returns the correct numbers …
> Store the latest copy of XML documents for serialisation

- iXBRLViewerPlugin/viewer/src/js/concept.js
- iXBRLViewerPlugin/viewer/src/js/summary.js
- iXBRLViewerPlugin/viewer/src/js/summary.test.js
See #758 - this was error was caused by generating a viewer without the relevant taxonomy being available, meaning that  definitions for dimensions were not available, resulting in a typed dimension being treated as an explicit dimension, and hitting the exception [here](https://github.com/Arelle/ixbrl-viewer/blob/master/iXBRLViewerPlugin/viewer/src/js/summary.js#L78). 
Add a property to `Concept` that allows us to check if the concept is backed by a taxonomy definition, and ignore dimensions missing definitions in the summary.
Generate a viewer with typed dimensions and a non-existent taxonomy, or generate a viewer and manually delete concept definitions for typed dimensions from the JSON and confirm that the viewer loads correctly.
**review**:
@Arelle/arelle
@paulwarren-wk
Fixes #758 .
> Tolerate missing dimension definitions when generating document summary.

- iXBRLViewerPlugin/viewer/src/less/text-block-viewer.less
The viewer pane and text block dialog iframes do not inherit CSS from the parent document, but they do have transparent backgrounds. [We hard code](https://github.com/Arelle/ixbrl-viewer/blob/bb2d91c07c675b17fd57754379dfab5b82613152/iXBRLViewerPlugin/viewer/src/less/inspector.less#L142-L143) the main viewer color and background-color values to black and white respectively, but did not for the text block viewer iframe. This caused the text block viewer pane to show black text on a black background when dark mode was enabled.
| Master | Master (with text selected) | PR |
| ------- | --------------------------- | --- |
| <img width="350" alt="Screenshot 2025-01-17 at 10 42 27 PM" src="https://github.com/user-attachments/assets/2dabaa18-3c6e-4440-9449-e4c9fe4f2337" /> | <img width="350" …
> Dark Mode: Text Block Viewer - Black Text on Black Background

- iXBRLViewerPlugin/viewer/src/html/footnote-details.html
- iXBRLViewerPlugin/viewer/src/js/footnote.js
- iXBRLViewerPlugin/viewer/src/js/inspector.js
- iXBRLViewerPlugin/viewer/src/less/inspector.less
A number of regressions in the behaviour when footnotes are focused in the inspector:
* Exception when fact is selected due to missing `readableValueHTML` method.
* Small glitch in top right of footnote display due to empty target document tag being shown.
* "show-all" ellipsis not disappearing after it is clicked.
* Missing icons in list of linked concepts.
* Implemented `readableValueHTML` for footnotes.
* Avoid calling `isNumeric` on footnotes.
* Added `property-table` class to footnote details table.
* Moved definition of `.select-icon` class so that apples to all fact lists.
Open a document with footnotes. Click on any footnote, and confirm that footnote is displayed correctly in fact inspector.
**review**:
@Arelle/arelle
@paulwarren-wk
> Various fixes for display of footnotes in inspector

- iXBRLViewerPlugin/viewer/src/js/viewer.js
- iXBRLViewerPlugin/viewer/src/less/viewer.less
Slow performance on documents with large numbers of sub-elements (absolutely position elements within `ix` elements)
This is follow-on to #806, and extends the approach of using CSS rules for highlighting sub elements within selected elements.
This gives significantly better performance when switching facts on documents with elements with large numbers of absolutely positioned sub elements.
Confirm that borders applied to elements on hover and selection are as before, but faster.
[This document](https://filings.xbrl.org/5493006QMFDDMYWIAM13/2023-12-31/ESEF/ES/0/) shows the performance issue - open the document and press the previous fact button to select one of the problematic facts at the end of the document.
**review**:
@Arelle/arelle
@paulwarren-wk
> Use CSS rules for element selection

- iXBRLViewerPlugin/viewer/src/js/inspector.js
- iXBRLViewerPlugin/viewer/src/js/util.js
User language selection for the application interface is lost on reload or when navigating between viewers.
* Store user application language selection in local storage.
* During load, check if the application language was previously set in local storage.
* Explicit query param language still takes precedence.
* Change application language.
* Refresh.
* Confirm application language persists.
**review**:
@Arelle/arelle
@paulwarren-wk
> Persist App Language Selection to Local Storage

- iXBRLViewerPlugin/viewer/src/i18n/cy/translation.json
- iXBRLViewerPlugin/viewer/src/i18n/en/translation.json
- iXBRLViewerPlugin/viewer/src/i18n/es/translation.json
- iXBRLViewerPlugin/viewer/src/js/inspector.js
- iXBRLViewerPlugin/viewer/src/js/ixbrlviewer.js
- iXBRLViewerPlugin/viewer/src/js/theme.js
- iXBRLViewerPlugin/viewer/src/js/util.js
- iXBRLViewerPlugin/viewer/src/less/inspector.less
Reopening #684. The previous discussion moved into changing the application language. That feature is being handled by another effort.
We currently set the lang attribute to a default of en-US for all non stub viewers.
* Use [a report with a non English xml:lang value](https://github.com/Arelle/ixbrl-viewer/files/15476117/austin-2024-05-28-fr.zip).
* Verify that the lang attribute on the root HTML node reflects the application UI language and is updated when you change it.
* Verify that for the non-stub viewer, that all attributes of the report document are migrated to the iframe HTML node for the report document.
* Verify that that the lang attribute on the report document iframe HTML nodes reflects the xml:lang attribute from the filing.
**review**:
@Arelle/arelle
@paulwarren-wk
> Migrate lang attributes to iframe documents and remove default

- iXBRLViewerPlugin/viewer/src/js/util.js
- iXBRLViewerPlugin/viewer/src/less/colours.less
- iXBRLViewerPlugin/viewer/src/less/inspector.less
- iXBRLViewerPlugin/viewer/src/less/viewer.less
Requested by FRC
Add three more highlight colors:
Open document with more than three namespaces and confirm that additional colors are shown in viewer and key.
**review**:
@Arelle/arelle
@paulwarren-wk
> Add additional highlight colors

- iXBRLViewerPlugin/viewer/src/js/viewer.js
Bug: when "highlight all tags" is selected, continuation elements are always shown in the default highlight color, regardless of namespace.
This was a regression introduced in e3b91fefab26d5b9eff1250a73e13dce29fcae1f : the continuation code was refactored, but in doing so, we were no longer setting `.continuations` on `IXNode`.
This introduces a new step in the document preparation process to set the `.continuations` property on all `IXNode`s.
Confirm that in a document with multiple namespaces, any facts with continuation content are highlighted in the right color.
**review**:
@Arelle/arelle
@paulwarren-wk
> Fix highlighting of continuations.

- .github/workflows/build-documentation.yml
- README.md
We should provide a link to the [RTD project](https://arelle-ixbrl-viewer.readthedocs.io/).
* Include a link to RTD in README.
* Add badges to README
* Add TOC to README.
* Add license link to README.
* Add contributors section to README.
* Misc README cleanup.
* CI
**review**:
@Arelle/arelle
@paulwarren-wk
> Add RTD link to README

- iXBRLViewerPlugin/viewer/src/js/inspector.js
- iXBRLViewerPlugin/viewer/src/js/ixbrlviewer.js
- iXBRLViewerPlugin/viewer/src/js/ixbrlviewer.test.js
- iXBRLViewerPlugin/viewer/src/js/util.js
When the user guide feature is not enabled, fall back to the URL for the lastest ixbrl-viewer RTD documentation.
Add User Guide link to the header as well.
Note: I considered linking to the documentation version that matched the version of the viewer being used, but felt that wouldn't be best due to the user guide being in an early state right now.
CI
**review**:
@Arelle/arelle
@paulwarren-wk
> Fall back to RTD user guide for Help > User Guide link

- iXBRLViewerPlugin/viewer/src/js/util.js
I'm linking to the latest version instead of the current viewer's version because I expect user guide coverage to grow, and I'd prefer people see the version of the guide with the most coverage and only small discrepancies (hopefully).
**review**:
@Arelle/arelle
@paulwarren-wk
> Update user guide link to actual user guide

- iXBRLViewerPlugin/viewer/src/less/inspector.less
`<button>` elements have their own styling applied by user agent stylesheets. This overrides the default font used elsewhere in the viewer (see #821), leading to inconsistent fonts.
Fixes #821
Specify our standard default font for `<button>` elements. I've also removed the `#ixv` scope of all inspector CSS rules. This is unnecessary, and dates back to _very_ early version of the viewer that didn't use iframes.
See examples on #821. Confirm that font is now consistent.
**review**:
@Arelle/arelle
@paulwarren-wk
> Apply default font to button elements.

- iXBRLViewerPlugin/viewer/src/js/viewer.js
Tags being mislabelled as "concealed facts".
Fixes #815
We try to use table cells as wrapper nodes where possible, because it makes fact highlighting neater. Some reports are using table cells with "display: contents" in order to get the semantics of tables (required for some ESEF reports) without interfering with layout. Attempting to use these as wrapper nodes will never give us what we want, and leads to other problems, as described in #815.
Confirm that facts on test doc on #815 are no longer mislabelled as concealed.
**review**:
@Arelle/arelle
@paulwarren-wk
> Avoid using hidden table cells as wrapper nodes

- iXBRLViewerPlugin/viewer/src/js/inspector.js
- iXBRLViewerPlugin/viewer/src/js/util.js
FRC suggested that calculation mode switch was confusing.
Adds a feature called `hide_calculation_mode_option` that can be specified to remove the Calculations 1.1 option from the options menu.
This can be specified in the usual ways, including via the runtime config
Open a filing with calculations, confirm that Calc 1.1 option is present on the menu.
Add:
```json
"features": {
"hide_calculation_mode_option": true
},
```
to `ixbrlviewer.config.json`.
Reload viewer and confirm that Calc 1.1 option is no longer present.
**review**:
@Arelle/arelle
@paulwarren-wk
> Add feature to disable calculation 1.1 mode option

- iXBRLViewerPlugin/viewer/src/js/unit.js
- iXBRLViewerPlugin/viewer/src/js/unit.test.js
- iXBRLViewerPlugin/viewer/src/js/utr.js
I noticed that the measure labels (units) displayed in the viewer used the symbols from the UTR for currencies (so £ is displayed instead of GBP) but the symbols for other measures were not.
If you want to report an area using square meters, you need to use a measure of `utr:sqm` in your unit, which ixbrl-viewer will display as "sqm" with a tool tip of "Square metre". ixbrl-viewer should be displaying "m²" with a tool tip of "Square metre"
Previously, currencies would use their symbol for their measure label but not other units. Shuffle the code around so that now all units will use their symbol if they have one defined and, if not, fall back to using their unit id as before.
In `utr.js`, which defines objects `UTR` and `UTREntry`, if a symbol was undefined for a given `UTREntry`, the …
> Enhancement: Use symbols in UTR for all units that have them defined (not just currencies)

- iXBRLViewerPlugin/viewer/src/js/inspector.js
"User Guide" link is duplicated in toolbar and dropdown menu.
Remove dropdown link in favor of more discoverable toolbar link.
CI
**review**:
@Arelle/arelle
@paulwarren-wk
> Remove User Guide link from dropdown

- .github/workflows/build-documentation.yml
- .github/workflows/puppeteer.yml
- .github/workflows/python-package.yml
- .github/workflows/python-tests.yml
- .readthedocs.yaml
- README.md
- pyproject.toml
- tox.ini
https://github.com/Arelle/Arelle/pull/1615 added Python 3.13 support to Arelle. We should update our ixbrl-viewer builds to use it.
* Run tests against Python 3.13.
* List Python 3.13 support in the Python Package.
* CI
**review**:
@Arelle/arelle
@paulwarren-wk
> Python 3.13 Support

- iXBRLViewerPlugin/viewer/src/less/tabs.less
Dark mode color styling missing for tabs that appear with multiple documents.
**review**:
@Arelle/arelle
@paulwarren-wk
> Improved dark mode for multiple documents/tabs

- iXBRLViewerPlugin/viewer/src/js/inspector.js
Some text in the search pane doesn't update immediately upon language switch. 
Refresh the search pane by performing the search function when language is switched.
With search results open, change language. Ensure "Showing X of Y" and "Hidden Fact" text changes to the translated text immediately.
**review**:
@Arelle/arelle
@paulwarren-wk
> Refresh search on language change
