Arelle/ixbrl-viewer

setup.py

- Bump version to 0.1.5
- CI
review:
@Workiva/xmas

XMAS-3817 - Bump ixbrl-viewer version to 0.1.5

---

iXBRLViewerPlugin/iXBRLViewer.py
iXBRLViewerPlugin/viewer/src/html/inspector.html
iXBRLViewerPlugin/viewer/src/js/accordian.js
iXBRLViewerPlugin/viewer/src/js/concept.js
iXBRLViewerPlugin/viewer/src/js/concept.test.js
iXBRLViewerPlugin/viewer/src/js/inspector.js
iXBRLViewerPlugin/viewer/src/js/search.js
iXBRLViewerPlugin/viewer/src/less/inspector.less

Incorporate taxonomy reference information into the viewer.

Viewer references

---

iXBRLViewerPlugin/viewer/src/js/moment-jest.js
iXBRLViewerPlugin/viewer/src/js/period.js
iXBRLViewerPlugin/viewer/src/js/period.test.js
iXBRLViewerPlugin/viewer/src/js/util.js
iXBRLViewerPlugin/viewer/src/js/util.test.js
iXBRLViewerPlugin/viewer/webpack.common.js
package.json

Fix the issue with date tests failing mentioned in issue #12.

Timezone fix

---

setup.py

Bumped ixbrl-viewer version from 0.1.5 to 0.1.6 in preparation for release
CI
Review:
@Workiva/xmas

XMAS-3918 - Bump ixbrl-viewer version to 0.1.6

---

Dockerfile
iXBRLViewerPlugin/viewer/src/less/chart.less
iXBRLViewerPlugin/viewer/src/less/common.less
iXBRLViewerPlugin/viewer/src/less/core.less
iXBRLViewerPlugin/viewer/src/less/dialog.less
iXBRLViewerPlugin/viewer/src/less/fonts.less
iXBRLViewerPlugin/viewer/src/less/form-controls.less
iXBRLViewerPlugin/viewer/src/less/icons.less
iXBRLViewerPlugin/viewer/src/less/inspector.less
iXBRLViewerPlugin/viewer/src/less/menu.less
iXBRLViewerPlugin/viewer/src/less/text-mixins.less
iXBRLViewerPlugin/viewer/src/less/viewer.less
package.json

Use stylelint to check .less files, and apply fixes/formatting changes needed to get a clean report.
Adds "npm run stylelint" target, and adds this to the Dockerfile to ensure that the check remains clean.

Stylelint - CSS tidying

---

iXBRLViewerPlugin/iXBRLViewer.py
setup.py

- Fixed a future warning around a None check
- Bumped version to 0.1.7
- Create a viewer and verify that the future warning is fixed
**review**:
@Workiva/xmas

XMAS-4195 - Fix future warning and bump version

---

iXBRLViewerPlugin/xhtmlserialize.py

Remove dependency on Python 3.6+ syntax

---

iXBRLViewerPlugin/viewer/src/js/period.test.js

Additional tests for various formats of period within the JSON block.

Additional test for handling of periods.

---

Dockerfile
setup.py

Add GIT_TAG to Dockerfile and pull for it in setup.py to set the version number.
- CI
**review**:
@Workiva/xmas

XMAS-4198 - Automate version bumping

---

iXBRLViewerPlugin/iXBRLViewer.py
iXBRLViewerPlugin/viewer/src/js/inspector.js
iXBRLViewerPlugin/viewer/src/js/period.js
iXBRLViewerPlugin/viewer/src/js/period.test.js

The test document I often use has missing periods for some facts, which causes the iXBRL viewer to hang during loading.
@Workiva/xmas
@paulwarren-wk

XMAS-3573: Tolerate missing period

---

Dockerfile
setup.py

-Inject version into setup.py via sed so that setup.py retains version info in pypi artifact
- CI
**review**:
@Workiva/xmas

XMAS-4399 - Update auto versioning to permanently change setup.py during build

---

iXBRLViewerPlugin/viewer/src/js/inspector.js
iXBRLViewerPlugin/viewer/src/js/viewer.js
samples/src/continuation/continuation.html

This adds support for facts with content split across multiple blocks with ix:continuation.

Add support for ix:continuation

---

Dockerfile
package.json

- See ticket description
- Verify that the artifacts contain the following two files:
- build/ixbrl-viewer-0.0.0.tgz and that it has type npm
- build/dist/ixbrl_viewer-0.0.0.tar.gz and that it has type pypi
**review**:
@Workiva/xmas

XMAS-5631 - Add npm package creation

---

Dockerfile

- Fix updating setup.py and package.py with the correct version based on GIT_TAG
- CI
**review**:
@Workiva/xmas

XMAS-5645 - Fix version setting for releases

---

Dockerfile

- Add new arg for github upload
- CI
**review**:
@Workiva/xt

XT-268 - Upload ixbrlviewer.js to github after its been generated

---

Dockerfile

- Narrow sed command down to affect build versions rather than dependency versions
- Build locally
**review**:
@Workiva/xt

XT-406 - Update sed command to be more specific

---

iXBRLViewerPlugin/iXBRLViewer.py

- Protect against NPE when a null concept is added
- Create a fact without a concept
@Workiva/xt  @paulwarren-wk

XT-651 Protect against null concept

---

iXBRLViewerPlugin/__init__.py
iXBRLViewerPlugin/iXBRLViewer.py
iXBRLViewerPlugin/localviewer.py

changes to integrate with EdgarRenderer, POST uploads and zip downloads via REST API; tolerate nonfatal instance errors in partially-constructed instances

arelle integration pull request for Edgar 20.3

---

tests/unit_tests/iXBRLViewerPlugin/mock_arelle.py
tests/unit_tests/iXBRLViewerPlugin/test_iXBRLViewer.py

- Fix arelle mock so that it can run unit tests correctly
- Fix mocks so that relationshipSets work correctly
- CI
**review**:
@Workiva/xt

XT-1030 - Fix unit tests

---

package.json

Reverts Workiva/ixbrl-viewer#156

Revert "Bump css-loader from 3.6.0 to 5.0.1"

---

package.json

Reverts Workiva/ixbrl-viewer#155

Revert "Bump webpack-cli from 3.3.12 to 4.2.0"

---

package.json

Reverts Workiva/ixbrl-viewer#158

Revert "Bump less-loader from 6.2.0 to 7.1.0"

---

iXBRLViewerPlugin/viewer/src/html/inspector.html
iXBRLViewerPlugin/viewer/src/js/ixbrlviewer.js

This PR addresses accessibility issues listed on this report:
https://www.webaccessibility.com/results/?url=https%3A%2F%2Fwww.workiva.com%2Fsites%2Fworkiva%2Ffiles%2F2020-01%2Fixbrl_viewer-45fa445867ef4917ab19c7fad4c1f507-results_4%2Fixbrl-viewer.htm

Accessibility fixes

---

requirements-dev.txt
requirements.txt

- Add ranges to dependencies to reduce possible downstream dependency conflicts.
- CI
**review**:
@Workiva/xt

XT-1491 - Add ranges to dependencies

---

Dockerfile
README.md
setup.py

XT-1836: Update to python 3.9

---

setup.py

Update author email to reflect team XT
CI
**review:**
@Workiva/xt

Update author email to reflect team XT

---

.github/dependabot.yml

https://jira.atl.workiva.net/browse/XT-2090
**review**:
@Workiva/xt

XT-2090: Run dependabot daily at 2 AM

---

.github/dependabot.yml
package.json

XT-2200: Ignore stylelint updates incompatible with Docker build (node 10)

---

iXBRLViewerPlugin/viewer/src/js/accordian.js
iXBRLViewerPlugin/viewer/src/js/factset.js
iXBRLViewerPlugin/viewer/src/js/footnote.js
iXBRLViewerPlugin/viewer/src/js/identifiers.js
iXBRLViewerPlugin/viewer/src/js/index.js
iXBRLViewerPlugin/viewer/src/js/ixnode.js
iXBRLViewerPlugin/viewer/src/js/menu.js
iXBRLViewerPlugin/viewer/src/js/outline.js
iXBRLViewerPlugin/viewer/src/js/period.js
iXBRLViewerPlugin/viewer/src/js/qname.js
iXBRLViewerPlugin/viewer/src/js/search.js
iXBRLViewerPlugin/viewer/src/js/tableExport.js
iXBRLViewerPlugin/viewer/src/js/util.js

This continuation is an extension of #335, rolling out the same updates to use more modern JS to additional source files.
To aid review, I've tried to keep the refactor to use class syntax in separate commits from [other changes](https://github.com/Workiva/ixbrl-viewer/pull/336/files/f43a05407aa0950ca0924bbcd57aeda8e26fd6e3..e64ece2daf5429a0b7b3be08536fc7ab1bc78144)

Code update

---

iXBRLViewerPlugin/xhtmlserialize.py
tests/unit_tests/iXBRLViewerPlugin/test_xhtmlserialize.py

Fixes the issue described by #341
Generate an ixbrl-vewer with and without this fix and verify this fixes the highlighting issues
@Workiva/xt @paulwarren-wk @brettkail-wk

#341 Fix: self closing tag serialization issue

---

iXBRLViewerPlugin/viewer/src/js/util.js
iXBRLViewerPlugin/viewer/src/js/util.test.js

Fixes #347 
@Workiva/xt @paulwarren-wk

Fix truncation

---

Dockerfile
iXBRLViewerPlugin/viewer/webpack.common.js
iXBRLViewerPlugin/viewer/webpack.dev.js
iXBRLViewerPlugin/viewer/webpack.prod.js
package.json

Update dependencies and Dockerfile for node v19.

Update node version to 19

---

.github/dependabot.yml

Dependabot updates node and python patch versions in Dockerfile, transient Python dependencies
CI
@Workiva/xt

Dependabot for Dockerfile, transient Python dependencies

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/questions.yml
.github/ISSUE_TEMPLATE/request.yml
.github/PULL_REQUEST_TEMPLATE.md

- Addresses https://github.com/Workiva/ixbrl-viewer/issues/351, and https://github.com/Workiva/ixbrl-viewer/issues/350
- CI
@Workiva/xt 
@paulwarren-wk

XT-2742 Add issue and pr templates

---

.gitignore
iXBRLViewerPlugin/iXBRLViewer.py
requirements-dev.txt
tests/unit_tests/iXBRLViewerPlugin/test_iXBRLViewer.py

Fixes bug introduced by https://github.com/Workiva/ixbrl-viewer/pull/371/files
CI
**review**:
@Workiva/xt
@paulwarren-wk

XT-2765 Pass filenames to docSetFiles

---

iXBRLViewerPlugin/viewer/src/html/inspector.html
iXBRLViewerPlugin/viewer/src/js/ixbrlviewer.js
iXBRLViewerPlugin/viewer/src/less/inspector.less
iXBRLViewerPlugin/viewer/webpack.common.js
package.json

Reverts Workiva/ixbrl-viewer#392

Revert "Include version number in viewer"

---

.gitignore

build artifact isn't in gitignore
ignore build artifacts
* CI
**review**:
@Workiva/xt
@paulwarren-wk

git ignore npm pack artifact

---

.github/dependabot.yml

Dependabot now supports grouping updates into a single PR
* Formatting
* Configure Dependabot to group PRs
* CI
**review**:
@Workiva/xt
@paulwarren-wk

XT-3071: Group Dependabot PRs

---

.github/dependabot.yml
iXBRLViewerPlugin/viewer/src/less/inspector.less
iXBRLViewerPlugin/viewer/src/less/menu.less
iXBRLViewerPlugin/viewer/src/less/viewer.less
package-lock.json
package.json

Moving stylelint to a separate Dependabot group as updates often require code changes
Update stylelint and resolve errors
* CI
**review**:
@Workiva/xt
@paulwarren-wk

XT-3080 Update stylelint

---

iXBRLViewerPlugin/viewer/src/js/ixbrlviewer.js
iXBRLViewerPlugin/viewer/src/js/report.js
iXBRLViewerPlugin/viewer/src/js/reportset.js

Code modernisation.
Update `ixbrlviewer.js`, `report.js` and `reportset.js` to use more modern JavaScript.
This should be a pure re-factor, with no change in functionality.
**review**:
@Arelle/arelle
@paulwarren-wk

Modernize JavaScript

---

Makefile

**review**:
@Arelle/arelle
@paulwarren-wk

Fix JS paths in the makefile.

---

iXBRLViewerPlugin/viewer/src/i18n/cy/translation.json
iXBRLViewerPlugin/viewer/src/i18n/en/translation.json
iXBRLViewerPlugin/viewer/src/i18n/es/translation.json
iXBRLViewerPlugin/viewer/src/js/inspector.js

Changed "Report an Issue" text to "Contact Us"
Build a viewer and observe the new text.
**review**:
@Arelle/arelle
@paulwarren-wk

Changed "Report an Issue" text to "Contact Us"

---

iXBRLViewerPlugin/viewer/src/i18n/cy/translation.json
iXBRLViewerPlugin/viewer/src/i18n/es/translation.json

Add translation in Spanish and Welsh.
* CI
**review**:
@Arelle/arelle
@paulwarren-wk

Translate XBRL glossary new tab text

---

iXBRLViewerPlugin/__init__.py

**review**:
@Arelle/arelle
@paulwarren-wk

Log exceptions at a level higher than INFO.
